/** Bilmodell-databas – uppdaterad 2026-03-09 via scripts/update-cars.mjs */

export type CarSize = "compact" | "medium" | "suv" | "premium";
export type UseCase = "city" | "commuter" | "family" | "adventure" | "premium";

export interface EvModel {
  id: string;
  brand: string;
  model: string;
  priceSek: number;
  rangeKm: number;
  batteryKwh: number;
  kwhPerMile: number;
  size: CarSize;
  useCases: UseCase[];
  seats: number;
  trunkLiters: number;
  fastChargeMin: number;
  year: number;
  description: string;
  emoji: string;
  towbar: boolean;
  awd: boolean;
}

export const EV_MODELS: EvModel[] = [
  {
    id: "volvo-ex30",
    brand: "Volvo",
    model: "EX30 Single Motor",
    priceSek: 429_000,
    rangeKm: 275,
    batteryKwh: 49,
    kwhPerMile: 1.78,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 318,
    fastChargeMin: 27,
    year: 2025,
    description: "SUV (JB - Compact). Rackvidd 275 km, batteri 49 kWh.",
    emoji: "🇸🇪",
    towbar: false,
    awd: false,
  },
  {
    id: "mg4",
    brand: "MG",
    model: "MG4 Electric 64 kWh",
    priceSek: 369_990,
    rangeKm: 360,
    batteryKwh: 61.7,
    kwhPerMile: 1.71,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 363,
    fastChargeMin: 25,
    year: 2025,
    description: "Hatchback (C - Medium). Rackvidd 360 km, batteri 61.7 kWh.",
    emoji: "💰",
    towbar: false,
    awd: false,
  },
  {
    id: "byd-atto3",
    brand: "BYD",
    model: "ATTO 3",
    priceSek: 484_900,
    rangeKm: 330,
    batteryKwh: 60.5,
    kwhPerMile: 1.83,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 440,
    fastChargeMin: 38,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 330 km, batteri 60.5 kWh.",
    emoji: "💰",
    towbar: false,
    awd: false,
  },
  {
    id: "cupra-born",
    brand: "CUPRA",
    model: "Born 170 kW - 79 kWh",
    priceSek: 485_900,
    rangeKm: 470,
    batteryKwh: 79,
    kwhPerMile: 1.68,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 385,
    fastChargeMin: 26,
    year: 2025,
    description: "Hatchback (C - Medium). Rackvidd 470 km, batteri 79 kWh.",
    emoji: "🏎️",
    towbar: false,
    awd: false,
  },
  {
    id: "bmw-ix1",
    brand: "BMW",
    model: "iX1 xDrive30",
    priceSek: 563_900,
    rangeKm: 380,
    batteryKwh: 64.7,
    kwhPerMile: 1.7,
    size: "compact",
    useCases: ["commuter","premium"],
    seats: 5,
    trunkLiters: 490,
    fastChargeMin: 33,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 380 km, batteri 64.7 kWh.",
    emoji: "✨",
    towbar: true,
    awd: true,
  },
  {
    id: "kia-ev3",
    brand: "Kia",
    model: "EV3 Long Range",
    priceSek: 508_300,
    rangeKm: 455,
    batteryKwh: 78,
    kwhPerMile: 1.71,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 460,
    fastChargeMin: 33,
    year: 2025,
    description: "SUV (JB - Compact). Rackvidd 455 km, batteri 78 kWh.",
    emoji: "🔋",
    towbar: false,
    awd: false,
  },
  {
    id: "skoda-elroq",
    brand: "Škoda",
    model: "Elroq 85",
    priceSek: 569_900,
    rangeKm: 450,
    batteryKwh: 77,
    kwhPerMile: 1.71,
    size: "compact",
    useCases: ["city","commuter","family"],
    seats: 5,
    trunkLiters: 470,
    fastChargeMin: 28,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 450 km, batteri 77 kWh.",
    emoji: "🚗",
    towbar: true,
    awd: false,
  },
  {
    id: "vw-id3",
    brand: "Volkswagen",
    model: "ID.3 Pro S",
    priceSek: 488_900,
    rangeKm: 475,
    batteryKwh: 79,
    kwhPerMile: 1.66,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 385,
    fastChargeMin: 26,
    year: 2025,
    description: "Hatchback (C - Medium). Rackvidd 475 km, batteri 79 kWh.",
    emoji: "🚗",
    towbar: false,
    awd: false,
  },
  {
    id: "peugeot-e208",
    brand: "Peugeot",
    model: "e-208 54 kWh",
    priceSek: 359_900,
    rangeKm: 335,
    batteryKwh: 50.8,
    kwhPerMile: 1.52,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 309,
    fastChargeMin: 28,
    year: 2025,
    description: "Hatchback (B - Compact). Rackvidd 335 km, batteri 50.8 kWh.",
    emoji: "🇫🇷",
    towbar: false,
    awd: false,
  },
  {
    id: "fiat-500e",
    brand: "Fiat",
    model: "500e Hatchback 42 kWh",
    priceSek: 326_900,
    rangeKm: 235,
    batteryKwh: 37.3,
    kwhPerMile: 1.59,
    size: "compact",
    useCases: ["city"],
    seats: 4,
    trunkLiters: 185,
    fastChargeMin: 25,
    year: 2025,
    description: "Hatchback (B - Compact). Rackvidd 235 km, batteri 37.3 kWh.",
    emoji: "🇮🇹",
    towbar: false,
    awd: false,
  },
  {
    id: "opel-corsa-e",
    brand: "Opel",
    model: "Corsa Electric 54 kWh",
    priceSek: 369_900,
    rangeKm: 335,
    batteryKwh: 50.8,
    kwhPerMile: 1.52,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 267,
    fastChargeMin: 28,
    year: 2025,
    description: "Hatchback (B - Compact). Rackvidd 335 km, batteri 50.8 kWh.",
    emoji: "🚗",
    towbar: false,
    awd: false,
  },
  {
    id: "mini-cooper-se",
    brand: "Mini",
    model: "Cooper SE",
    priceSek: 431_900,
    rangeKm: 330,
    batteryKwh: 49.2,
    kwhPerMile: 1.49,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 4,
    trunkLiters: 200,
    fastChargeMin: 29,
    year: 2025,
    description: "Hatchback (B - Compact). Rackvidd 330 km, batteri 49.2 kWh.",
    emoji: "🇬🇧",
    towbar: false,
    awd: false,
  },
  {
    id: "smart-1",
    brand: "Smart",
    model: "#1 Pro",
    priceSek: 419_900,
    rangeKm: 250,
    batteryKwh: 47,
    kwhPerMile: 1.88,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 323,
    fastChargeMin: 32,
    year: 2025,
    description: "SUV (JB - Compact). Rackvidd 250 km, batteri 47 kWh.",
    emoji: "🚗",
    towbar: false,
    awd: false,
  },
  {
    id: "smart-3",
    brand: "Smart",
    model: "#3 Pro",
    priceSek: 429_900,
    rangeKm: 265,
    batteryKwh: 47,
    kwhPerMile: 1.77,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 370,
    fastChargeMin: 32,
    year: 2025,
    description: "SUV (JB - Compact). Rackvidd 265 km, batteri 47 kWh.",
    emoji: "🏎️",
    towbar: false,
    awd: false,
  },
  {
    id: "citroen-ec4",
    brand: "Citroën",
    model: "ë-C4",
    priceSek: 399_900,
    rangeKm: 285,
    batteryKwh: 46.3,
    kwhPerMile: 1.62,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 380,
    fastChargeMin: 28,
    year: 2025,
    description: "Hatchback (C - Medium). Rackvidd 285 km, batteri 46.3 kWh.",
    emoji: "🇫🇷",
    towbar: false,
    awd: false,
  },
  {
    id: "nissan-leaf",
    brand: "Nissan",
    model: "LEAF Extended Range 75 kWh",
    priceSek: 429_900,
    rangeKm: 460,
    batteryKwh: 75.1,
    kwhPerMile: 1.63,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 437,
    fastChargeMin: 32,
    year: 2025,
    description: "Liftback Sedan (C - Medium). Rackvidd 460 km, batteri 75.1 kWh.",
    emoji: "🍃",
    towbar: false,
    awd: false,
  },
  {
    id: "opel-mokka-e",
    brand: "Opel",
    model: "Mokka Electric",
    priceSek: 399_900,
    rangeKm: 285,
    batteryKwh: 50.8,
    kwhPerMile: 1.78,
    size: "compact",
    useCases: ["city","commuter"],
    seats: 5,
    trunkLiters: 310,
    fastChargeMin: 28,
    year: 2025,
    description: "SUV (JB - Compact). Rackvidd 285 km, batteri 50.8 kWh.",
    emoji: "🚗",
    towbar: false,
    awd: false,
  },
  {
    id: "peugeot-e2008",
    brand: "Peugeot",
    model: "e-2008 54 kWh",
    priceSek: 519_900,
    rangeKm: 300,
    batteryKwh: 50.8,
    kwhPerMile: 1.69,
    size: "compact",
    useCases: ["city","commuter","family"],
    seats: 5,
    trunkLiters: 434,
    fastChargeMin: 28,
    year: 2025,
    description: "SUV (JB - Compact). Rackvidd 300 km, batteri 50.8 kWh.",
    emoji: "🇫🇷",
    towbar: false,
    awd: false,
  },
  {
    id: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3 Premium RWD",
    priceSek: 519_990,
    rangeKm: 580,
    batteryKwh: 79,
    kwhPerMile: 1.36,
    size: "medium",
    useCases: ["commuter","family"],
    seats: 5,
    trunkLiters: 594,
    fastChargeMin: 28,
    year: 2025,
    description: "Sedan (D - Large). Rackvidd 580 km, batteri 79 kWh.",
    emoji: "⚡",
    towbar: true,
    awd: false,
  },
  {
    id: "byd-seal",
    brand: "BYD",
    model: "SEAL 82.5 kWh RWD Design",
    priceSek: 589_900,
    rangeKm: 480,
    batteryKwh: 82.5,
    kwhPerMile: 1.72,
    size: "medium",
    useCases: ["commuter","family"],
    seats: 5,
    trunkLiters: 400,
    fastChargeMin: 36,
    year: 2025,
    description: "Sedan (D - Large). Rackvidd 480 km, batteri 82.5 kWh.",
    emoji: "🦭",
    towbar: false,
    awd: false,
  },
  {
    id: "polestar-2",
    brand: "Polestar",
    model: "2 Long Range Single Motor",
    priceSek: 489_000,
    rangeKm: 475,
    batteryKwh: 79,
    kwhPerMile: 1.66,
    size: "medium",
    useCases: ["commuter","premium"],
    seats: 5,
    trunkLiters: 407,
    fastChargeMin: 32,
    year: 2025,
    description: "Liftback Sedan (D - Large). Rackvidd 475 km, batteri 79 kWh.",
    emoji: "✨",
    towbar: true,
    awd: false,
  },
  {
    id: "hyundai-ioniq6",
    brand: "Hyundai",
    model: "IONIQ 6 84 kWh RWD",
    priceSek: 589_900,
    rangeKm: 545,
    batteryKwh: 80,
    kwhPerMile: 1.47,
    size: "medium",
    useCases: ["commuter","premium"],
    seats: 5,
    trunkLiters: 401,
    fastChargeMin: 18,
    year: 2025,
    description: "Sedan (D - Large). Rackvidd 545 km, batteri 80 kWh.",
    emoji: "💨",
    towbar: false,
    awd: false,
  },
  {
    id: "vw-id7",
    brand: "Volkswagen",
    model: "ID.7 Pro S",
    priceSek: 664_900,
    rangeKm: 525,
    batteryKwh: 86,
    kwhPerMile: 1.64,
    size: "medium",
    useCases: ["commuter","family"],
    seats: 5,
    trunkLiters: 532,
    fastChargeMin: 26,
    year: 2025,
    description: "Liftback Sedan (E - Executive). Rackvidd 525 km, batteri 86 kWh.",
    emoji: "🚗",
    towbar: true,
    awd: false,
  },
  {
    id: "vw-id7-tourer",
    brand: "Volkswagen",
    model: "ID.7 Tourer Pro S",
    priceSek: 690_000,
    rangeKm: 520,
    batteryKwh: 86,
    kwhPerMile: 1.65,
    size: "medium",
    useCases: ["family","commuter"],
    seats: 5,
    trunkLiters: 605,
    fastChargeMin: 26,
    year: 2025,
    description: "Station/Estate (E - Executive). Rackvidd 520 km, batteri 86 kWh.",
    emoji: "🚗",
    towbar: true,
    awd: false,
  },
  {
    id: "kia-ev6",
    brand: "Kia",
    model: "EV6 Long Range 2WD",
    priceSek: 599_900,
    rangeKm: 455,
    batteryKwh: 80,
    kwhPerMile: 1.76,
    size: "medium",
    useCases: ["commuter","family","adventure"],
    seats: 5,
    trunkLiters: 490,
    fastChargeMin: 17,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 455 km, batteri 80 kWh.",
    emoji: "🔋",
    towbar: true,
    awd: false,
  },
  {
    id: "renault-megane",
    brand: "Renault",
    model: "Megane E-Tech EV60 220hp",
    priceSek: 449_900,
    rangeKm: 380,
    batteryKwh: 60,
    kwhPerMile: 1.58,
    size: "medium",
    useCases: ["commuter","family"],
    seats: 5,
    trunkLiters: 440,
    fastChargeMin: 33,
    year: 2025,
    description: "Hatchback (C - Medium). Rackvidd 380 km, batteri 60 kWh.",
    emoji: "🇫🇷",
    towbar: false,
    awd: false,
  },
  {
    id: "bmw-i4",
    brand: "BMW",
    model: "i4 eDrive40",
    priceSek: 599_900,
    rangeKm: 525,
    batteryKwh: 81.3,
    kwhPerMile: 1.55,
    size: "medium",
    useCases: ["commuter","premium"],
    seats: 5,
    trunkLiters: 470,
    fastChargeMin: 28,
    year: 2025,
    description: "Liftback Sedan (D - Large). Rackvidd 525 km, batteri 81.3 kWh.",
    emoji: "✨",
    towbar: true,
    awd: false,
  },
  {
    id: "tesla-model-y",
    brand: "Tesla",
    model: "Model Y Long Range RWD",
    priceSek: 574_990,
    rangeKm: 490,
    batteryKwh: 77,
    kwhPerMile: 1.57,
    size: "suv",
    useCases: ["family","adventure"],
    seats: 5,
    trunkLiters: 835,
    fastChargeMin: 26,
    year: 2025,
    description: "SUV (JD - Large). Rackvidd 490 km, batteri 77 kWh.",
    emoji: "🚙",
    towbar: true,
    awd: false,
  },
  {
    id: "volvo-ex40",
    brand: "Volvo",
    model: "EX40 Single Motor ER",
    priceSek: 607_000,
    rangeKm: 400,
    batteryKwh: 79,
    kwhPerMile: 1.98,
    size: "suv",
    useCases: ["family","commuter"],
    seats: 5,
    trunkLiters: 410,
    fastChargeMin: 32,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 400 km, batteri 79 kWh.",
    emoji: "🇸🇪",
    towbar: true,
    awd: false,
  },
  {
    id: "volvo-ex60",
    brand: "Volvo",
    model: "EX60 P6",
    priceSek: 689_000,
    rangeKm: 455,
    batteryKwh: 80,
    kwhPerMile: 1.76,
    size: "suv",
    useCases: ["family","premium"],
    seats: 5,
    trunkLiters: 523,
    fastChargeMin: 19,
    year: 2025,
    description: "SUV (JD - Large). Rackvidd 455 km, batteri 80 kWh.",
    emoji: "🇸🇪",
    towbar: true,
    awd: false,
  },
  {
    id: "vw-id4",
    brand: "Volkswagen",
    model: "ID.4 Pro",
    priceSek: 586_900,
    rangeKm: 445,
    batteryKwh: 77,
    kwhPerMile: 1.73,
    size: "suv",
    useCases: ["family","commuter"],
    seats: 5,
    trunkLiters: 543,
    fastChargeMin: 28,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 445 km, batteri 77 kWh.",
    emoji: "🚗",
    towbar: true,
    awd: false,
  },
  {
    id: "vw-id5",
    brand: "Volkswagen",
    model: "ID.5 Pro",
    priceSek: 613_900,
    rangeKm: 455,
    batteryKwh: 77,
    kwhPerMile: 1.69,
    size: "suv",
    useCases: ["family","commuter"],
    seats: 5,
    trunkLiters: 549,
    fastChargeMin: 28,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 455 km, batteri 77 kWh.",
    emoji: "🚗",
    towbar: true,
    awd: false,
  },
  {
    id: "kia-ev5",
    brand: "Kia",
    model: "EV5 81.4 kWh",
    priceSek: 553_900,
    rangeKm: 400,
    batteryKwh: 78,
    kwhPerMile: 1.95,
    size: "suv",
    useCases: ["family","commuter"],
    seats: 5,
    trunkLiters: 566,
    fastChargeMin: 30,
    year: 2025,
    description: "SUV (C - Medium). Rackvidd 400 km, batteri 78 kWh.",
    emoji: "🔋",
    towbar: true,
    awd: false,
  },
  {
    id: "hyundai-ioniq5",
    brand: "Hyundai",
    model: "IONIQ 5 84 kWh RWD",
    priceSek: 519_900,
    rangeKm: 450,
    batteryKwh: 80,
    kwhPerMile: 1.78,
    size: "suv",
    useCases: ["family","commuter"],
    seats: 5,
    trunkLiters: 520,
    fastChargeMin: 18,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 450 km, batteri 80 kWh.",
    emoji: "⚡",
    towbar: true,
    awd: false,
  },
  {
    id: "skoda-enyaq",
    brand: "Škoda",
    model: "Enyaq 85",
    priceSek: 569_900,
    rangeKm: 455,
    batteryKwh: 77,
    kwhPerMile: 1.69,
    size: "suv",
    useCases: ["family","adventure"],
    seats: 5,
    trunkLiters: 585,
    fastChargeMin: 28,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 455 km, batteri 77 kWh.",
    emoji: "🧳",
    towbar: true,
    awd: false,
  },
  {
    id: "byd-seal-u",
    brand: "BYD",
    model: "SEAL U 87 kWh Design",
    priceSek: 469_900,
    rangeKm: 425,
    batteryKwh: 87,
    kwhPerMile: 2.05,
    size: "suv",
    useCases: ["family","commuter"],
    seats: 5,
    trunkLiters: 552,
    fastChargeMin: 45,
    year: 2025,
    description: "SUV (JD - Large). Rackvidd 425 km, batteri 87 kWh.",
    emoji: "💰",
    towbar: false,
    awd: false,
  },
  {
    id: "byd-sealion7",
    brand: "BYD",
    model: "SEALION 7 82.5 kWh RWD Comfort",
    priceSek: 569_900,
    rangeKm: 420,
    batteryKwh: 82.5,
    kwhPerMile: 1.96,
    size: "suv",
    useCases: ["family","adventure"],
    seats: 5,
    trunkLiters: 520,
    fastChargeMin: 32,
    year: 2025,
    description: "SUV (JD - Large). Rackvidd 420 km, batteri 82.5 kWh.",
    emoji: "🦁",
    towbar: false,
    awd: false,
  },
  {
    id: "ford-explorer",
    brand: "Ford",
    model: "Explorer Extended Range RWD",
    priceSek: 489_900,
    rangeKm: 450,
    batteryKwh: 79,
    kwhPerMile: 1.76,
    size: "suv",
    useCases: ["family","commuter"],
    seats: 5,
    trunkLiters: 532,
    fastChargeMin: 26,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 450 km, batteri 79 kWh.",
    emoji: "🚙",
    towbar: true,
    awd: false,
  },
  {
    id: "renault-scenic",
    brand: "Renault",
    model: "Scenic E-Tech EV87 220hp",
    priceSek: 549_900,
    rangeKm: 480,
    batteryKwh: 87,
    kwhPerMile: 1.81,
    size: "suv",
    useCases: ["family","commuter"],
    seats: 5,
    trunkLiters: 545,
    fastChargeMin: 40,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 480 km, batteri 87 kWh.",
    emoji: "🇫🇷",
    towbar: true,
    awd: false,
  },
  {
    id: "nissan-ariya",
    brand: "Nissan",
    model: "Ariya 87kWh",
    priceSek: 513_500,
    rangeKm: 450,
    batteryKwh: 87,
    kwhPerMile: 1.93,
    size: "suv",
    useCases: ["family","commuter"],
    seats: 5,
    trunkLiters: 468,
    fastChargeMin: 48,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 450 km, batteri 87 kWh.",
    emoji: "🚙",
    towbar: true,
    awd: false,
  },
  {
    id: "peugeot-e3008",
    brand: "Peugeot",
    model: "e-3008 73 kWh",
    priceSek: 499_900,
    rangeKm: 380,
    batteryKwh: 73,
    kwhPerMile: 1.92,
    size: "suv",
    useCases: ["family","commuter"],
    seats: 5,
    trunkLiters: 588,
    fastChargeMin: 36,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 380 km, batteri 73 kWh.",
    emoji: "🇫🇷",
    towbar: true,
    awd: false,
  },
  {
    id: "toyota-bz4x",
    brand: "Toyota",
    model: "bZ4X Touring AWD 74.7 kWh",
    priceSek: 479_900,
    rangeKm: 385,
    batteryKwh: 71,
    kwhPerMile: 1.84,
    size: "suv",
    useCases: ["family","adventure"],
    seats: 5,
    trunkLiters: 600,
    fastChargeMin: 29,
    year: 2025,
    description: "SUV (JD - Large). Rackvidd 385 km, batteri 71 kWh.",
    emoji: "🚙",
    towbar: true,
    awd: true,
  },
  {
    id: "xpeng-g6",
    brand: "XPENG",
    model: "G6 RWD Long Range",
    priceSek: 579_900,
    rangeKm: 435,
    batteryKwh: 80,
    kwhPerMile: 1.84,
    size: "suv",
    useCases: ["commuter","family"],
    seats: 5,
    trunkLiters: 571,
    fastChargeMin: 12,
    year: 2025,
    description: "SUV (JD - Large). Rackvidd 435 km, batteri 80 kWh.",
    emoji: "🇨🇳",
    towbar: false,
    awd: false,
  },
  {
    id: "mercedes-eqa",
    brand: "Mercedes-Benz",
    model: "EQA 250",
    priceSek: 615_000,
    rangeKm: 395,
    batteryKwh: 66.5,
    kwhPerMile: 1.68,
    size: "suv",
    useCases: ["commuter","premium"],
    seats: 5,
    trunkLiters: 340,
    fastChargeMin: 29,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 395 km, batteri 66.5 kWh.",
    emoji: "✨",
    towbar: true,
    awd: false,
  },
  {
    id: "mercedes-eqb",
    brand: "Mercedes-Benz",
    model: "EQB 250+",
    priceSek: 592_900,
    rangeKm: 415,
    batteryKwh: 70.5,
    kwhPerMile: 1.7,
    size: "suv",
    useCases: ["family","premium"],
    seats: 7,
    trunkLiters: 495,
    fastChargeMin: 35,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 415 km, batteri 70.5 kWh.",
    emoji: "✨",
    towbar: true,
    awd: false,
  },
  {
    id: "audi-q4-etron",
    brand: "Audi",
    model: "Q4 e-tron 45",
    priceSek: 625_200,
    rangeKm: 420,
    batteryKwh: 77,
    kwhPerMile: 1.83,
    size: "suv",
    useCases: ["commuter","premium"],
    seats: 5,
    trunkLiters: 520,
    fastChargeMin: 28,
    year: 2025,
    description: "SUV (JC - Medium). Rackvidd 420 km, batteri 77 kWh.",
    emoji: "✨",
    towbar: true,
    awd: false,
  },
  {
    id: "audi-q6-etron",
    brand: "Audi",
    model: "Q6 SUV e-tron",
    priceSek: 789_900,
    rangeKm: 395,
    batteryKwh: 75.8,
    kwhPerMile: 1.92,
    size: "suv",
    useCases: ["family","premium"],
    seats: 5,
    trunkLiters: 526,
    fastChargeMin: 22,
    year: 2025,
    description: "SUV (JD - Large). Rackvidd 395 km, batteri 75.8 kWh.",
    emoji: "✨",
    towbar: true,
    awd: false,
  },
  {
    id: "bmw-ix3",
    brand: "BMW",
    model: "iX3 50 xDrive",
    priceSek: 749_000,
    rangeKm: 610,
    batteryKwh: 108.7,
    kwhPerMile: 1.78,
    size: "suv",
    useCases: ["family","premium"],
    seats: 5,
    trunkLiters: 520,
    fastChargeMin: 21,
    year: 2025,
    description: "SUV (JD - Large). Rackvidd 610 km, batteri 108.7 kWh.",
    emoji: "✨",
    towbar: true,
    awd: true,
  },
  {
    id: "volvo-ex90",
    brand: "Volvo",
    model: "EX90 Single Motor",
    priceSek: 899_000,
    rangeKm: 425,
    batteryKwh: 88,
    kwhPerMile: 2.07,
    size: "premium",
    useCases: ["family","premium","adventure"],
    seats: 7,
    trunkLiters: 669,
    fastChargeMin: 23,
    year: 2025,
    description: "SUV (JF - Luxury). Rackvidd 425 km, batteri 88 kWh.",
    emoji: "👑",
    towbar: true,
    awd: false,
  },
  {
    id: "kia-ev9",
    brand: "Kia",
    model: "EV9 99.8 kWh RWD",
    priceSek: 701_900,
    rangeKm: 450,
    batteryKwh: 96,
    kwhPerMile: 2.13,
    size: "premium",
    useCases: ["family","adventure"],
    seats: 7,
    trunkLiters: 333,
    fastChargeMin: 22,
    year: 2025,
    description: "SUV (JF - Luxury). Rackvidd 450 km, batteri 96 kWh.",
    emoji: "🏔️",
    towbar: true,
    awd: false,
  },
  {
    id: "vw-id-buzz",
    brand: "Volkswagen",
    model: "ID. Buzz LWB Pro",
    priceSek: 646_900,
    rangeKm: 390,
    batteryKwh: 86,
    kwhPerMile: 2.21,
    size: "premium",
    useCases: ["family","adventure"],
    seats: 7,
    trunkLiters: 1340,
    fastChargeMin: 26,
    year: 2025,
    description: "Small Passenger Van (N - Passenger Van). Rackvidd 390 km, batteri 86 kWh.",
    emoji: "🚌",
    towbar: true,
    awd: false,
  },
  {
    id: "polestar-3",
    brand: "Polestar",
    model: "3 Rear Motor",
    priceSek: 924_000,
    rangeKm: 440,
    batteryKwh: 88,
    kwhPerMile: 2,
    size: "premium",
    useCases: ["premium","adventure"],
    seats: 5,
    trunkLiters: 484,
    fastChargeMin: 23,
    year: 2025,
    description: "SUV (JE - Executive). Rackvidd 440 km, batteri 88 kWh.",
    emoji: "✨",
    towbar: true,
    awd: false,
  },
  {
    id: "bmw-ix",
    brand: "BMW",
    model: "iX xDrive40",
    priceSek: 940_000,
    rangeKm: 360,
    batteryKwh: 71,
    kwhPerMile: 1.97,
    size: "premium",
    useCases: ["premium","adventure"],
    seats: 5,
    trunkLiters: 500,
    fastChargeMin: 34,
    year: 2025,
    description: "SUV (JE - Executive). Rackvidd 360 km, batteri 71 kWh.",
    emoji: "👑",
    towbar: true,
    awd: true,
  },
  {
    id: "porsche-taycan",
    brand: "Porsche",
    model: "Taycan",
    priceSek: 1_170_000,
    rangeKm: 495,
    batteryKwh: 82.3,
    kwhPerMile: 1.66,
    size: "premium",
    useCases: ["premium","commuter"],
    seats: 5,
    trunkLiters: 407,
    fastChargeMin: 19,
    year: 2025,
    description: "Sedan (F - Luxury). Rackvidd 495 km, batteri 82.3 kWh.",
    emoji: "🏎️",
    towbar: false,
    awd: false,
  },
];

export function getModelById(id: string): EvModel | undefined {
  return EV_MODELS.find((m) => m.id === id);
}

export function getModelsBySize(size: CarSize): EvModel[] {
  return EV_MODELS.filter((m) => m.size === size);
}

export function getModelsByUseCase(useCase: UseCase): EvModel[] {
  return EV_MODELS.filter((m) => m.useCases.includes(useCase));
}

export function getModelsByBudget(maxSek: number): EvModel[] {
  return EV_MODELS.filter((m) => m.priceSek <= maxSek).sort((a, b) => a.priceSek - b.priceSek);
}

export function formatSek(amount: number): string {
  return new Intl.NumberFormat("sv-SE", { style: "currency", currency: "SEK", maximumFractionDigits: 0 }).format(amount);
}

const BRAND_COUNTRY: Record<string, string> = {
  Volvo: "SE", Polestar: "SE",
  Volkswagen: "DE", VW: "DE", BMW: "DE", "Mercedes-Benz": "DE", Audi: "DE", Porsche: "DE", Opel: "DE", Smart: "DE",
  Mini: "GB", MINI: "GB", CUPRA: "ES",
  "\u0160koda": "CZ", Skoda: "CZ",
  Kia: "KR", Hyundai: "KR",
  BYD: "CN", MG: "CN", XPENG: "CN",
  Tesla: "US", Ford: "US",
  Peugeot: "FR", "Citro\u00ebn": "FR", Renault: "FR",
  Fiat: "IT", Nissan: "JP", Toyota: "JP",
};

export function brandFlag(brand: string): string {
  return BRAND_COUNTRY[brand] ?? "";
}

// ── Fossila referensbilar ────────────────────────────────────────────────────

export interface FossilModel {
  id: string;
  brand: string;
  model: string;
  priceSek: number;
  fuelType: "petrol" | "diesel";
  litersPerMile: number;
  size: CarSize;
  taxAnnual: number;
  insuranceAnnual: number;
}

export const FOSSIL_MODELS: FossilModel[] = [
  // Kompakt
  { id: "vw-golf", brand: "VW", model: "Golf 1.5 TSI", priceSek: 310_000, fuelType: "petrol", litersPerMile: 0.55, size: "compact", taxAnnual: 4_200, insuranceAnnual: 4_000 },
  { id: "toyota-corolla", brand: "Toyota", model: "Corolla 1.8 Hybrid", priceSek: 295_000, fuelType: "petrol", litersPerMile: 0.43, size: "compact", taxAnnual: 3_800, insuranceAnnual: 3_800 },
  { id: "skoda-octavia", brand: "Skoda", model: "Octavia 1.5 TSI", priceSek: 285_000, fuelType: "petrol", litersPerMile: 0.54, size: "compact", taxAnnual: 4_100, insuranceAnnual: 3_700 },
  { id: "kia-ceed", brand: "Kia", model: "Ceed 1.5 T-GDI", priceSek: 265_000, fuelType: "petrol", litersPerMile: 0.56, size: "compact", taxAnnual: 4_300, insuranceAnnual: 3_500 },
  // Mellanklass
  { id: "volvo-v60", brand: "Volvo", model: "V60 B3 Bensin", priceSek: 380_000, fuelType: "petrol", litersPerMile: 0.62, size: "medium", taxAnnual: 5_200, insuranceAnnual: 5_200 },
  { id: "toyota-camry", brand: "Toyota", model: "Camry 2.5 Hybrid", priceSek: 370_000, fuelType: "petrol", litersPerMile: 0.45, size: "medium", taxAnnual: 4_000, insuranceAnnual: 4_800 },
  { id: "vw-passat", brand: "VW", model: "Passat 1.5 TSI", priceSek: 365_000, fuelType: "petrol", litersPerMile: 0.58, size: "medium", taxAnnual: 5_000, insuranceAnnual: 4_900 },
  { id: "skoda-superb", brand: "Skoda", model: "Superb 1.5 TSI", priceSek: 355_000, fuelType: "petrol", litersPerMile: 0.57, size: "medium", taxAnnual: 4_800, insuranceAnnual: 4_500 },
  // SUV
  { id: "volvo-xc60", brand: "Volvo", model: "XC60 B5 Bensin", priceSek: 490_000, fuelType: "petrol", litersPerMile: 0.75, size: "suv", taxAnnual: 6_500, insuranceAnnual: 6_200 },
  { id: "toyota-rav4", brand: "Toyota", model: "RAV4 2.5 Hybrid", priceSek: 420_000, fuelType: "petrol", litersPerMile: 0.52, size: "suv", taxAnnual: 4_500, insuranceAnnual: 5_500 },
  { id: "vw-tiguan", brand: "VW", model: "Tiguan 1.5 TSI", priceSek: 400_000, fuelType: "petrol", litersPerMile: 0.65, size: "suv", taxAnnual: 5_500, insuranceAnnual: 5_200 },
  { id: "kia-sportage", brand: "Kia", model: "Sportage 1.6 T-GDI", priceSek: 385_000, fuelType: "petrol", litersPerMile: 0.68, size: "suv", taxAnnual: 5_800, insuranceAnnual: 4_800 },
];
