/** Bilmodell-databas – uppdaterad 2026-02-19 via scripts/update-cars.mjs + manuella tillägg */

export type CarSize = "compact" | "medium" | "suv" | "premium";
export type UseCase = "city" | "commuter" | "family" | "adventure" | "premium";

export interface EvModel {
  id: string;
  brand: string;
  model: string;
  priceSek: number;
  rangeKm: number;
  batteryKwh: number;
  kwhPerMile: number;
  size: CarSize;
  useCases: UseCase[];
  seats: number;
  trunkLiters: number;
  fastChargeMin: number;
  year: number;
  description: string;
  emoji: string;
}

export const EV_MODELS: EvModel[] = [
  // ── Kompakt ───────────────────────────────────────────────────────────────
  {
    id: "volvo-ex30",
    brand: "Volvo",
    model: "EX30 Single Motor",
    priceSek: 349_900,
    rangeKm: 275,
    batteryKwh: 49,
    kwhPerMile: 1.78,
    size: "compact",
    useCases: ["city", "commuter"],
    seats: 5,
    trunkLiters: 318,
    fastChargeMin: 27,
    year: 2025,
    description: "Kompakt Volvo med hög säkerhet. Perfekt för stad och kortare pendling.",
    emoji: "🇸🇪",
  },
  {
    id: "mg4",
    brand: "MG",
    model: "MG4 Electric 64 kWh",
    priceSek: 279_900,
    rangeKm: 360,
    batteryKwh: 61.7,
    kwhPerMile: 1.72,
    size: "compact",
    useCases: ["city", "commuter"],
    seats: 5,
    trunkLiters: 363,
    fastChargeMin: 24,
    year: 2025,
    description: "En av marknadens billigaste elbilar. Bra utrustning för pengarna.",
    emoji: "💰",
  },
  {
    id: "byd-atto3",
    brand: "BYD",
    model: "ATTO 3",
    priceSek: 329_900,
    rangeKm: 330,
    batteryKwh: 60.5,
    kwhPerMile: 1.83,
    size: "compact",
    useCases: ["city", "commuter"],
    seats: 5,
    trunkLiters: 440,
    fastChargeMin: 37,
    year: 2025,
    description: "Prisvärd kompakt-SUV från världens största elbilstillverkare.",
    emoji: "💰",
  },
  {
    id: "cupra-born",
    brand: "CUPRA",
    model: "Born 79 kWh",
    priceSek: 389_900,
    rangeKm: 470,
    batteryKwh: 79,
    kwhPerMile: 1.68,
    size: "compact",
    useCases: ["city", "commuter"],
    seats: 5,
    trunkLiters: 385,
    fastChargeMin: 26,
    year: 2025,
    description: "Sportig kompakt med lång räckvidd. VW-plattform med attityd.",
    emoji: "🏎️",
  },
  {
    id: "bmw-ix1",
    brand: "BMW",
    model: "iX1 xDrive30",
    priceSek: 499_900,
    rangeKm: 380,
    batteryKwh: 64.7,
    kwhPerMile: 1.70,
    size: "compact",
    useCases: ["commuter", "premium"],
    seats: 5,
    trunkLiters: 490,
    fastChargeMin: 30,
    year: 2025,
    description: "Kompakt premium-SUV med BMW-körupplevelse.",
    emoji: "✨",
  },
  {
    id: "kia-ev3",
    brand: "Kia",
    model: "EV3 Long Range",
    priceSek: 389_900,
    rangeKm: 455,
    batteryKwh: 78,
    kwhPerMile: 1.71,
    size: "compact",
    useCases: ["city", "commuter"],
    seats: 5,
    trunkLiters: 460,
    fastChargeMin: 33,
    year: 2025,
    description: "Kompakt SUV med imponerande räckvidd och V2L-funktion.",
    emoji: "🔋",
  },
  {
    id: "skoda-elroq",
    brand: "Škoda",
    model: "Elroq 85",
    priceSek: 399_900,
    rangeKm: 450,
    batteryKwh: 77,
    kwhPerMile: 1.71,
    size: "compact",
    useCases: ["city", "commuter", "family"],
    seats: 5,
    trunkLiters: 470,
    fastChargeMin: 28,
    year: 2025,
    description: "Praktisk kompakt-SUV med Škodas Simply Clever-lösningar.",
    emoji: "🚗",
  },
  {
    id: "vw-id3",
    brand: "Volkswagen",
    model: "ID.3 Pro S",
    priceSek: 369_900,
    rangeKm: 475,
    batteryKwh: 79,
    kwhPerMile: 1.66,
    size: "compact",
    useCases: ["city", "commuter"],
    seats: 5,
    trunkLiters: 385,
    fastChargeMin: 26,
    year: 2025,
    description: "Volkswagens elbils-Golf. Lång räckvidd i kompakt format.",
    emoji: "🚗",
  },

  // ── Mellanklass / Sedan ───────────────────────────────────────────────────
  {
    id: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3 Premium RWD",
    priceSek: 399_900,
    rangeKm: 580,
    batteryKwh: 79,
    kwhPerMile: 1.36,
    size: "medium",
    useCases: ["commuter", "family"],
    seats: 5,
    trunkLiters: 594,
    fastChargeMin: 29,
    year: 2025,
    description: "Populäraste elbilen. Bäst i klassen på räckvidd och laddning.",
    emoji: "⚡",
  },
  {
    id: "byd-seal",
    brand: "BYD",
    model: "SEAL 82.5 kWh RWD",
    priceSek: 419_900,
    rangeKm: 480,
    batteryKwh: 82.5,
    kwhPerMile: 1.72,
    size: "medium",
    useCases: ["commuter", "family"],
    seats: 5,
    trunkLiters: 400,
    fastChargeMin: 36,
    year: 2025,
    description: "Tesla Model 3-konkurrent med lång räckvidd och konkurrenskraftigt pris.",
    emoji: "🦭",
  },
  {
    id: "polestar-2",
    brand: "Polestar",
    model: "2 Long Range",
    priceSek: 459_900,
    rangeKm: 475,
    batteryKwh: 79,
    kwhPerMile: 1.66,
    size: "medium",
    useCases: ["commuter", "premium"],
    seats: 5,
    trunkLiters: 405,
    fastChargeMin: 32,
    year: 2025,
    description: "Skandinavisk design, sportig körupplevelse. Google-infotainment.",
    emoji: "✨",
  },
  {
    id: "hyundai-ioniq6",
    brand: "Hyundai",
    model: "IONIQ 6 84 kWh",
    priceSek: 479_900,
    rangeKm: 545,
    batteryKwh: 80,
    kwhPerMile: 1.47,
    size: "medium",
    useCases: ["commuter", "premium"],
    seats: 5,
    trunkLiters: 401,
    fastChargeMin: 17,
    year: 2025,
    description: "Aerodynamisk sedan med enastående effektivitet och ultrasnabb laddning.",
    emoji: "💨",
  },
  {
    id: "vw-id7",
    brand: "Volkswagen",
    model: "ID.7 Pro S",
    priceSek: 549_900,
    rangeKm: 525,
    batteryKwh: 86,
    kwhPerMile: 1.64,
    size: "medium",
    useCases: ["commuter", "family"],
    seats: 5,
    trunkLiters: 532,
    fastChargeMin: 26,
    year: 2025,
    description: "VW:s flaggskepp-sedan. Lång räckvidd och rymlig interiör.",
    emoji: "🚗",
  },
  {
    id: "vw-id7-tourer",
    brand: "Volkswagen",
    model: "ID.7 Tourer Pro S",
    priceSek: 569_900,
    rangeKm: 520,
    batteryKwh: 86,
    kwhPerMile: 1.65,
    size: "medium",
    useCases: ["family", "commuter"],
    seats: 5,
    trunkLiters: 605,
    fastChargeMin: 26,
    year: 2025,
    description: "Kombi-versionen av ID.7 med ännu mer lastutrymme.",
    emoji: "🚗",
  },

  // ── SUV / Familj ──────────────────────────────────────────────────────────
  {
    id: "tesla-model-y",
    brand: "Tesla",
    model: "Model Y Long Range RWD",
    priceSek: 449_900,
    rangeKm: 490,
    batteryKwh: 77,
    kwhPerMile: 1.57,
    size: "suv",
    useCases: ["family", "adventure"],
    seats: 5,
    trunkLiters: 854,
    fastChargeMin: 26,
    year: 2025,
    description: "Världens mest sålda elbil. Rymlig familje-SUV.",
    emoji: "🚙",
  },
  {
    id: "volvo-ex40",
    brand: "Volvo",
    model: "EX40 Single Motor ER",
    priceSek: 479_900,
    rangeKm: 400,
    batteryKwh: 79,
    kwhPerMile: 1.98,
    size: "suv",
    useCases: ["family", "commuter"],
    seats: 5,
    trunkLiters: 452,
    fastChargeMin: 32,
    year: 2025,
    description: "Volvos mellanklassare med premiumkänsla.",
    emoji: "🇸🇪",
  },
  {
    id: "volvo-ex60",
    brand: "Volvo",
    model: "EX60 P6",
    priceSek: 599_900,
    rangeKm: 455,
    batteryKwh: 80,
    kwhPerMile: 1.76,
    size: "suv",
    useCases: ["family", "premium"],
    seats: 5,
    trunkLiters: 573,
    fastChargeMin: 19,
    year: 2026,
    description: "Efterföljaren till XC60. Mellanstor premium-SUV.",
    emoji: "🇸🇪",
  },
  {
    id: "vw-id4",
    brand: "Volkswagen",
    model: "ID.4 Pro",
    priceSek: 449_900,
    rangeKm: 445,
    batteryKwh: 77,
    kwhPerMile: 1.73,
    size: "suv",
    useCases: ["family", "commuter"],
    seats: 5,
    trunkLiters: 543,
    fastChargeMin: 28,
    year: 2025,
    description: "Välkänd familje-SUV. Rymlig, trygg och med bra infrastruktur.",
    emoji: "🚗",
  },
  {
    id: "vw-id5",
    brand: "Volkswagen",
    model: "ID.5 Pro",
    priceSek: 469_900,
    rangeKm: 455,
    batteryKwh: 77,
    kwhPerMile: 1.69,
    size: "suv",
    useCases: ["family", "commuter"],
    seats: 5,
    trunkLiters: 549,
    fastChargeMin: 28,
    year: 2025,
    description: "Coupé-SUV med samma teknik som ID.4 men sportigare profil.",
    emoji: "🚗",
  },
  {
    id: "kia-ev5",
    brand: "Kia",
    model: "EV5 81.4 kWh",
    priceSek: 429_900,
    rangeKm: 400,
    batteryKwh: 78,
    kwhPerMile: 1.95,
    size: "suv",
    useCases: ["family", "commuter"],
    seats: 5,
    trunkLiters: 566,
    fastChargeMin: 27,
    year: 2026,
    description: "Familjevänlig SUV med V2L och konkurrenskraftigt pris.",
    emoji: "🔋",
  },
  {
    id: "kia-ev6",
    brand: "Kia",
    model: "EV6 Long Range 2WD",
    priceSek: 499_900,
    rangeKm: 455,
    batteryKwh: 80,
    kwhPerMile: 1.76,
    size: "medium",
    useCases: ["commuter", "family", "adventure"],
    seats: 5,
    trunkLiters: 490,
    fastChargeMin: 17,
    year: 2025,
    description: "Ultrasnabb laddning (10→80% på 17 min). 800V-arkitektur.",
    emoji: "🔋",
  },
  {
    id: "hyundai-ioniq5",
    brand: "Hyundai",
    model: "IONIQ 5 84 kWh RWD",
    priceSek: 479_900,
    rangeKm: 450,
    batteryKwh: 80,
    kwhPerMile: 1.78,
    size: "suv",
    useCases: ["family", "commuter"],
    seats: 5,
    trunkLiters: 527,
    fastChargeMin: 17,
    year: 2025,
    description: "Snabb laddning och rymlig interiör. 800V som premium-bilarna.",
    emoji: "⚡",
  },
  {
    id: "skoda-enyaq",
    brand: "Škoda",
    model: "Enyaq 85",
    priceSek: 459_900,
    rangeKm: 455,
    batteryKwh: 77,
    kwhPerMile: 1.69,
    size: "suv",
    useCases: ["family", "adventure"],
    seats: 5,
    trunkLiters: 585,
    fastChargeMin: 28,
    year: 2025,
    description: "Rymlig familje-SUV med fokus på praktisk användning.",
    emoji: "🧳",
  },
  {
    id: "byd-seal-u",
    brand: "BYD",
    model: "SEAL U 87 kWh",
    priceSek: 399_900,
    rangeKm: 425,
    batteryKwh: 87,
    kwhPerMile: 2.05,
    size: "suv",
    useCases: ["family", "commuter"],
    seats: 5,
    trunkLiters: 425,
    fastChargeMin: 45,
    year: 2025,
    description: "Prisvärd familje-SUV med stort batteri.",
    emoji: "💰",
  },
  {
    id: "byd-sealion7",
    brand: "BYD",
    model: "SEALION 7 82.5 kWh RWD",
    priceSek: 449_900,
    rangeKm: 420,
    batteryKwh: 82.5,
    kwhPerMile: 1.96,
    size: "suv",
    useCases: ["family", "adventure"],
    seats: 5,
    trunkLiters: 520,
    fastChargeMin: 32,
    year: 2025,
    description: "Sportig SUV-coupé som utmanar Tesla Model Y.",
    emoji: "🦁",
  },
  {
    id: "ford-explorer",
    brand: "Ford",
    model: "Explorer Extended Range RWD",
    priceSek: 499_900,
    rangeKm: 450,
    batteryKwh: 79,
    kwhPerMile: 1.76,
    size: "suv",
    useCases: ["family", "commuter"],
    seats: 5,
    trunkLiters: 536,
    fastChargeMin: 26,
    year: 2025,
    description: "Fords el-SUV byggd på VW-plattform. Rymlig och välutrustad.",
    emoji: "🚙",
  },
  {
    id: "renault-scenic",
    brand: "Renault",
    model: "Scenic E-Tech EV87",
    priceSek: 449_900,
    rangeKm: 480,
    batteryKwh: 87,
    kwhPerMile: 1.81,
    size: "suv",
    useCases: ["family", "commuter"],
    seats: 5,
    trunkLiters: 545,
    fastChargeMin: 40,
    year: 2025,
    description: "Familje-SUV med stort bagageutrymme och lång räckvidd.",
    emoji: "🇫🇷",
  },

  // ── Stor / Premium ────────────────────────────────────────────────────────
  {
    id: "volvo-ex90",
    brand: "Volvo",
    model: "EX90 Single Motor",
    priceSek: 899_900,
    rangeKm: 425,
    batteryKwh: 88,
    kwhPerMile: 2.07,
    size: "premium",
    useCases: ["family", "premium", "adventure"],
    seats: 7,
    trunkLiters: 655,
    fastChargeMin: 23,
    year: 2025,
    description: "Volvos flaggskepp – 7-sitsig, premiuminteriör, avancerad säkerhet.",
    emoji: "👑",
  },
  {
    id: "kia-ev9",
    brand: "Kia",
    model: "EV9 99.8 kWh RWD",
    priceSek: 749_900,
    rangeKm: 450,
    batteryKwh: 96,
    kwhPerMile: 2.13,
    size: "premium",
    useCases: ["family", "adventure"],
    seats: 7,
    trunkLiters: 333,
    fastChargeMin: 22,
    year: 2025,
    description: "Stor 7-sitsig SUV med V2L. Imponerande utrymme.",
    emoji: "🏔️",
  },
  {
    id: "vw-id-buzz",
    brand: "Volkswagen",
    model: "ID. Buzz LWB Pro",
    priceSek: 649_900,
    rangeKm: 390,
    batteryKwh: 86,
    kwhPerMile: 2.21,
    size: "premium",
    useCases: ["family", "adventure"],
    seats: 7,
    trunkLiters: 306,
    fastChargeMin: 26,
    year: 2025,
    description: "Moderna folkabussen – 7 sitsplatser med retro-charm.",
    emoji: "🚌",
  },
  {
    id: "polestar-3",
    brand: "Polestar",
    model: "3 Rear Motor",
    priceSek: 799_900,
    rangeKm: 440,
    batteryKwh: 88,
    kwhPerMile: 2.00,
    size: "premium",
    useCases: ["premium", "adventure"],
    seats: 5,
    trunkLiters: 484,
    fastChargeMin: 23,
    year: 2025,
    description: "Skandinavisk premium-SUV med avancerad teknik.",
    emoji: "✨",
  },
];

export function getModelById(id: string): EvModel | undefined {
  return EV_MODELS.find((m) => m.id === id);
}

export function getModelsBySize(size: CarSize): EvModel[] {
  return EV_MODELS.filter((m) => m.size === size);
}

export function getModelsByUseCase(useCase: UseCase): EvModel[] {
  return EV_MODELS.filter((m) => m.useCases.includes(useCase));
}

export function getModelsByBudget(maxSek: number): EvModel[] {
  return EV_MODELS.filter((m) => m.priceSek <= maxSek).sort((a, b) => a.priceSek - b.priceSek);
}

export function formatSek(amount: number): string {
  return new Intl.NumberFormat("sv-SE", { style: "currency", currency: "SEK", maximumFractionDigits: 0 }).format(amount);
}

// ── Fossila referensbilar ────────────────────────────────────────────────────

export interface FossilModel {
  id: string;
  brand: string;
  model: string;
  priceSek: number;
  fuelType: "petrol" | "diesel";
  litersPerMile: number;
  size: CarSize;
  taxAnnual: number;
  insuranceAnnual: number;
}

export const FOSSIL_MODELS: FossilModel[] = [
  // Kompakt
  { id: "vw-golf", brand: "VW", model: "Golf 1.5 TSI", priceSek: 310_000, fuelType: "petrol", litersPerMile: 0.55, size: "compact", taxAnnual: 4_200, insuranceAnnual: 4_000 },
  { id: "toyota-corolla", brand: "Toyota", model: "Corolla 1.8 Hybrid", priceSek: 295_000, fuelType: "petrol", litersPerMile: 0.43, size: "compact", taxAnnual: 3_800, insuranceAnnual: 3_800 },
  { id: "skoda-octavia", brand: "Skoda", model: "Octavia 1.5 TSI", priceSek: 285_000, fuelType: "petrol", litersPerMile: 0.54, size: "compact", taxAnnual: 4_100, insuranceAnnual: 3_700 },
  { id: "kia-ceed", brand: "Kia", model: "Ceed 1.5 T-GDI", priceSek: 265_000, fuelType: "petrol", litersPerMile: 0.56, size: "compact", taxAnnual: 4_300, insuranceAnnual: 3_500 },
  // Mellanklass
  { id: "volvo-v60", brand: "Volvo", model: "V60 B3 Bensin", priceSek: 380_000, fuelType: "petrol", litersPerMile: 0.62, size: "medium", taxAnnual: 5_200, insuranceAnnual: 5_200 },
  { id: "toyota-camry", brand: "Toyota", model: "Camry 2.5 Hybrid", priceSek: 370_000, fuelType: "petrol", litersPerMile: 0.45, size: "medium", taxAnnual: 4_000, insuranceAnnual: 4_800 },
  { id: "vw-passat", brand: "VW", model: "Passat 1.5 TSI", priceSek: 365_000, fuelType: "petrol", litersPerMile: 0.58, size: "medium", taxAnnual: 5_000, insuranceAnnual: 4_900 },
  { id: "skoda-superb", brand: "Skoda", model: "Superb 1.5 TSI", priceSek: 355_000, fuelType: "petrol", litersPerMile: 0.57, size: "medium", taxAnnual: 4_800, insuranceAnnual: 4_500 },
  // SUV
  { id: "volvo-xc60", brand: "Volvo", model: "XC60 B5 Bensin", priceSek: 490_000, fuelType: "petrol", litersPerMile: 0.75, size: "suv", taxAnnual: 6_500, insuranceAnnual: 6_200 },
  { id: "toyota-rav4", brand: "Toyota", model: "RAV4 2.5 Hybrid", priceSek: 420_000, fuelType: "petrol", litersPerMile: 0.52, size: "suv", taxAnnual: 4_500, insuranceAnnual: 5_500 },
  { id: "vw-tiguan", brand: "VW", model: "Tiguan 1.5 TSI", priceSek: 400_000, fuelType: "petrol", litersPerMile: 0.65, size: "suv", taxAnnual: 5_500, insuranceAnnual: 5_200 },
  { id: "kia-sportage", brand: "Kia", model: "Sportage 1.6 T-GDI", priceSek: 385_000, fuelType: "petrol", litersPerMile: 0.68, size: "suv", taxAnnual: 5_800, insuranceAnnual: 4_800 },
];
