/**
 * Faktiska privatleasing-erbjudanden för elbilar i Sverige.
 *
 * Uppdateras manuellt ungefär en gång per månad.
 * Källor: elbilsmagasinet.se, tillverkares webbplatser, Wayke, Blocket.
 */

export interface LeasingOffer {
  id: string;
  brand: string;
  model: string;
  trim: string;
  monthlyPrice: number;
  downPayment: number;
  contractMonths: number;
  annualMileage: number;
  serviceIncluded: boolean;
  winterTiresIncluded: boolean;
  insuranceIncluded: boolean;
  rangeKm: number;
  batteryKwh: number;
  motorKw: number;
  size: "compact" | "medium" | "suv" | "premium";
  source: string;
  sourceUrl: string;
  note?: string;
}

const MONTH_NAMES_SV = [
  "januari", "februari", "mars", "april", "maj", "juni",
  "juli", "augusti", "september", "oktober", "november", "december",
];

/** Always returns "föregående månad" relative to now, e.g. "februari 2026". */
export function getLeasingPeriod(): string {
  const now = new Date();
  const prevMonth = now.getMonth() === 0 ? 11 : now.getMonth() - 1;
  const year = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear();
  return `${MONTH_NAMES_SV[prevMonth]} ${year}`;
}

export const LEASING_SOURCE_NOTE =
  "Priserna är hämtade från tillverkares webbplatser och elbilsmagasinet.se. Alla priser avser privatleasing exkl. eventuell startavgift. Erbjudanden kan ha ändrats sedan senaste uppdateringen.";

export const LEASING_OFFERS: LeasingOffer[] = [
  // ── Under 4 000 kr/mån ───────────────────────────────────────────────
  {
    id: "mini-cooper-e",
    brand: "Mini",
    model: "Cooper E",
    trim: "Standard",
    monthlyPrice: 3195,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 305,
    batteryKwh: 40.7,
    motorKw: 135,
    size: "compact",
    source: "Mini Sverige / Elbilsmagasinet",
    sourceUrl: "https://elbilsmagasinet.se/billigaste-elbilen-att-privatleasa/",
    note: "Kampanjpris på lagerbilar",
  },
  {
    id: "mg4-lr-luxury",
    brand: "MG",
    model: "MG4",
    trim: "Long Range Luxury",
    monthlyPrice: 3895,
    downPayment: 995,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 435,
    batteryKwh: 64,
    motorKw: 150,
    size: "compact",
    source: "MG Motor / Elbilsmagasinet",
    sourceUrl: "https://elbilsmagasinet.se/billigaste-elbilen-att-privatleasa/",
    note: "Startavgift 995 kr + admin 59 kr/mån tillkommer",
  },
  {
    id: "vw-id3-edition",
    brand: "Volkswagen",
    model: "ID.3",
    trim: "Edition",
    monthlyPrice: 3895,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 387,
    batteryKwh: 59,
    motorKw: 125,
    size: "compact",
    source: "Volkswagen / Elbilsmagasinet",
    sourceUrl: "https://elbilsmagasinet.se/billigaste-elbilen-att-privatleasa/",
  },
  {
    id: "volvo-ex30-core",
    brand: "Volvo",
    model: "EX30",
    trim: "Extended Range Core",
    monthlyPrice: 3995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 476,
    batteryKwh: 69,
    motorKw: 200,
    size: "compact",
    source: "Volvo Retail / Elbilsmagasinet",
    sourceUrl: "https://elbilsmagasinet.se/billigaste-elbilen-att-privatleasa/",
    note: "Kampanjpris via utvalda Volvohandlare",
  },

  // ── 4 000–5 000 kr/mån ───────────────────────────────────────────────
  {
    id: "zeekr-x-rwd",
    brand: "Zeekr",
    model: "X",
    trim: "Long Range RWD",
    monthlyPrice: 4290,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1500,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 440,
    batteryKwh: 66,
    motorKw: 200,
    size: "compact",
    source: "Zeekr / Elbilsmagasinet",
    sourceUrl: "https://elbilsmagasinet.se/billigaste-elbilen-att-privatleasa/",
    note: "1 500 mil/år ingår",
  },
  {
    id: "volvo-ex30-plus",
    brand: "Volvo",
    model: "EX30",
    trim: "Extended Range Plus",
    monthlyPrice: 4495,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 476,
    batteryKwh: 69,
    motorKw: 200,
    size: "compact",
    source: "Volvo / Elbilsmagasinet",
    sourceUrl: "https://elbilsmagasinet.se/billigaste-elbilen-att-privatleasa/",
  },
  {
    id: "byd-atto-3",
    brand: "BYD",
    model: "Atto 3",
    trim: "Standard",
    monthlyPrice: 3595,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 420,
    batteryKwh: 60.5,
    motorKw: 150,
    size: "suv",
    source: "BYD / Elbilsgurun",
    sourceUrl: "https://elbilsgurun.se/elbil-leasing-privat/privatleasing-av-elbil-2025-komplett-guide-jamforelse/",
  },
  {
    id: "byd-dolphin",
    brand: "BYD",
    model: "Dolphin",
    trim: "Standard",
    monthlyPrice: 3995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 340,
    batteryKwh: 44.9,
    motorKw: 70,
    size: "compact",
    source: "BYD / Elbilsgurun",
    sourceUrl: "https://elbilsgurun.se/elbil-leasing-privat/privatleasing-av-elbil-2025-komplett-guide-jamforelse/",
  },
  {
    id: "mg-zs-ev",
    brand: "MG",
    model: "ZS EV",
    trim: "Standard",
    monthlyPrice: 3690,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 320,
    batteryKwh: 51,
    motorKw: 130,
    size: "suv",
    source: "MG Motor / Elbilsgurun",
    sourceUrl: "https://elbilsgurun.se/elbil-leasing-privat/privatleasing-av-elbil-2025-komplett-guide-jamforelse/",
  },

  // ── 5 000–6 000 kr/mån ───────────────────────────────────────────────
  {
    id: "nissan-ariya-87",
    brand: "Nissan",
    model: "Ariya",
    trim: "e-FORCE 87 kWh AWD",
    monthlyPrice: 4995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: true,
    insuranceIncluded: false,
    rangeKm: 460,
    batteryKwh: 87,
    motorKw: 225,
    size: "suv",
    source: "Nissan / Elbilsmagasinet",
    sourceUrl: "https://elbilsmagasinet.se/billigaste-elbilen-att-privatleasa/",
    note: "Vinterdäck ingår. Fyrhjulsdrift.",
  },
  {
    id: "skoda-enyaq-85",
    brand: "Skoda",
    model: "Enyaq",
    trim: "85 Solid Edition",
    monthlyPrice: 5195,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 530,
    batteryKwh: 82,
    motorKw: 210,
    size: "suv",
    source: "Skoda / Elbilsmagasinet",
    sourceUrl: "https://elbilsmagasinet.se/billigaste-elbilen-att-privatleasa/",
    note: "Travel Assist och dragkrok ingår",
  },
  {
    id: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    trim: "Standard",
    monthlyPrice: 5495,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 513,
    batteryKwh: 60,
    motorKw: 208,
    size: "medium",
    source: "Tesla / Elbilsgurun",
    sourceUrl: "https://elbilsgurun.se/elbil-leasing-privat/privatleasing-av-elbil-2025-komplett-guide-jamforelse/",
  },
  {
    id: "vw-id4-pro",
    brand: "Volkswagen",
    model: "ID.4",
    trim: "Pro",
    monthlyPrice: 5495,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 530,
    batteryKwh: 82,
    motorKw: 210,
    size: "suv",
    source: "Volkswagen",
    sourceUrl: "https://www.volkswagen.se/sv/modeller/id4.html",
  },
  {
    id: "lynk-co-02",
    brand: "Lynk & Co",
    model: "02",
    trim: "Standard",
    monthlyPrice: 4995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 445,
    batteryKwh: 69,
    motorKw: 200,
    size: "compact",
    source: "Lynk & Co / Elbilsmagasinet",
    sourceUrl: "https://elbilsmagasinet.se/billigaste-elbilen-att-privatleasa/",
    note: "Säljs via Volvohandlare",
  },

  // ── 6 000+ kr/mån ────────────────────────────────────────────────────
  {
    id: "polestar-2",
    brand: "Polestar",
    model: "2",
    trim: "Long Range",
    monthlyPrice: 5984,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 540,
    batteryKwh: 79,
    motorKw: 220,
    size: "medium",
    source: "Polestar / Elbilsgurun",
    sourceUrl: "https://elbilsgurun.se/elbil-leasing-privat/privatleasing-av-elbil-2025-komplett-guide-jamforelse/",
  },
  {
    id: "tesla-model-y-lr",
    brand: "Tesla",
    model: "Model Y",
    trim: "Long Range AWD",
    monthlyPrice: 7090,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1500,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 533,
    batteryKwh: 75,
    motorKw: 378,
    size: "suv",
    source: "GoMore",
    sourceUrl: "https://gomore.se/en/leasing/electric-hybrid",
    note: "Fyrhjulsdrift. 1 500 mil/år.",
  },
  {
    id: "kia-ev6-lr",
    brand: "Kia",
    model: "EV6",
    trim: "Long Range RWD",
    monthlyPrice: 5990,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1500,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 528,
    batteryKwh: 77.4,
    motorKw: 168,
    size: "suv",
    source: "Kia Sverige",
    sourceUrl: "https://www.kia.com/se/modeller/ev6/",
  },
  {
    id: "hyundai-ioniq-5",
    brand: "Hyundai",
    model: "IONIQ 5",
    trim: "Long Range RWD",
    monthlyPrice: 5590,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1500,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 507,
    batteryKwh: 77.4,
    motorKw: 168,
    size: "suv",
    source: "Hyundai Sverige",
    sourceUrl: "https://www.hyundai.com/se/modeller/ioniq-5.html",
  },
];
