/**
 * Faktiska privatleasing-erbjudanden för elbilar i Sverige.
 *
 * Uppdateras manuellt ungefär en gång per månad.
 * Källor: tillverkarnas officiella webbplatser och stora återförsäljare.
 *
 * Senast uppdaterad: 2026-03-09
 */

export interface LeasingOffer {
  id: string;
  brand: string;
  model: string;
  trim: string;
  imageUrl?: string;
  monthlyPrice: number;
  downPayment: number;
  contractMonths: number;
  annualMileage: number;
  serviceIncluded: boolean;
  winterTiresIncluded: boolean;
  insuranceIncluded: boolean;
  rangeKm: number;
  batteryKwh: number;
  motorKw: number;
  size: "compact" | "medium" | "suv" | "premium";
  source: string;
  sourceUrl: string;
  note?: string;
}

const MONTH_NAMES_SV = [
  "januari", "februari", "mars", "april", "maj", "juni",
  "juli", "augusti", "september", "oktober", "november", "december",
];

export function getLeasingPeriod(): string {
  return "mars 2026";
}

export const LEASING_SOURCE_NOTE =
  "Priserna är hämtade direkt från tillverkarnas och återförsäljarnas officiella webbplatser. Alla priser avser privatleasing exkl. eventuell uppläggningsavgift och administrationsavgift om inget annat anges. Erbjudanden kan ha ändrats sedan senaste uppdateringen (mars 2026).";

export const LEASING_OFFERS: LeasingOffer[] = [
  // ── Under 4 000 kr/mån ───────────────────────────────────────────────
  {
    id: "vw-id3-edition",
    brand: "Volkswagen",
    model: "ID.3",
    trim: "Pro Edition",
    imageUrl: "/cars/volkswagen-id3.svg",
    monthlyPrice: 3995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 430,
    batteryKwh: 58,
    motorKw: 150,
    size: "compact",
    source: "Volkswagen Sverige",
    sourceUrl: "https://www.volkswagen.se/sv/kop-en-vw/erbjudanden.html",
    note: "Även fr. 2 937 kr/mån med 35 000 kr insats. Service ingår.",
  },
  {
    id: "cupra-born",
    brand: "CUPRA",
    model: "Born",
    trim: "Edition 59 kWh",
    imageUrl: "/cars/cupra-born.svg",
    monthlyPrice: 4195,
    downPayment: 10000,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 424,
    batteryKwh: 59,
    motorKw: 150,
    size: "compact",
    source: "CUPRA Sverige",
    sourceUrl: "https://www.cupraofficial.se/kopa/erbjudande/born/privat/cupra-born",
    note: "10 000 kr första förhöjd avgift.",
  },

  // ── 4 000–5 000 kr/mån ───────────────────────────────────────────────
  {
    id: "volvo-ex30-plus",
    brand: "Volvo",
    model: "EX30",
    trim: "Plus",
    imageUrl: "/cars/volvo-ex30.svg",
    monthlyPrice: 3995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 344,
    batteryKwh: 51,
    motorKw: 200,
    size: "compact",
    source: "Volvo Cars Sverige",
    sourceUrl: "https://www.volvocars.com/se/l/erbjudanden/ex30/",
    note: "Care by Volvo privatleasing. Rörlig ränta (Stibor 90).",
  },
  {
    id: "volvo-ex30-plus-er",
    brand: "Volvo",
    model: "EX30",
    trim: "Plus Extended Range",
    imageUrl: "/cars/volvo-ex30.svg",
    monthlyPrice: 4495,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 476,
    batteryKwh: 69,
    motorKw: 200,
    size: "compact",
    source: "Volvo Cars Sverige",
    sourceUrl: "https://www.volvocars.com/se/l/erbjudanden/ex30/",
    note: "Care by Volvo privatleasing. Rörlig ränta (Stibor 90).",
  },
  {
    id: "mercedes-eqa-250",
    brand: "Mercedes-Benz",
    model: "EQA",
    trim: "250+ Special Edition",
    imageUrl: "/cars/mercedes-eqa.svg",
    monthlyPrice: 4195,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 490,
    batteryKwh: 70.5,
    motorKw: 140,
    size: "suv",
    source: "Mercedes-Benz Sverige",
    sourceUrl: "https://www.mercedes-benz.se/passengercars/finance/offers-private.html",
    note: "4 195 kr/mån mån 1–12, därefter 5 195 kr/mån. Beställ senast 31 mars 2026.",
  },
  {
    id: "mercedes-eqb-250",
    brand: "Mercedes-Benz",
    model: "EQB",
    trim: "250+ Special Edition",
    imageUrl: "/cars/mercedes-eqb.svg",
    monthlyPrice: 4695,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 465,
    batteryKwh: 70.5,
    motorKw: 140,
    size: "suv",
    source: "Mercedes-Benz Sverige",
    sourceUrl: "https://www.mercedes-benz.se/passengercars/finance/offers-private.html",
    note: "4 695 kr/mån mån 1–12, därefter 5 695 kr/mån. 7-sitsig. Beställ senast 31 mars 2026.",
  },
  {
    id: "kia-ev3-lr",
    brand: "Kia",
    model: "EV3",
    trim: "Long Range",
    imageUrl: "/cars/kia-ev3.svg",
    monthlyPrice: 4695,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 600,
    batteryKwh: 81.4,
    motorKw: 150,
    size: "compact",
    source: "Kia Sverige",
    sourceUrl: "https://www.kia.com/se/kopa/privatleasing/",
    note: "7 års garanti. Uppläggningsavgift 995 kr + admin 59 kr/mån.",
  },
  {
    id: "bmw-ix1",
    brand: "BMW",
    model: "iX1",
    trim: "eDrive20",
    imageUrl: "/cars/bmw-ix1.svg",
    monthlyPrice: 4795,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 440,
    batteryKwh: 64.7,
    motorKw: 150,
    size: "suv",
    source: "BMW Sverige",
    sourceUrl: "https://www.bmw.se/sv/bmw-financial-services-oversikt/erbjudanden/privaterbjudanden.html",
    note: "5-års servicepaket ingår. Vinterdäck +395 kr/mån. Övermil 12,50 kr/mil.",
  },
  {
    id: "kia-ev3-gt-line",
    brand: "Kia",
    model: "EV3",
    trim: "GT Line Long Range",
    imageUrl: "/cars/kia-ev3.svg",
    monthlyPrice: 5495,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 600,
    batteryKwh: 81.4,
    motorKw: 150,
    size: "compact",
    source: "Kia Sverige",
    sourceUrl: "https://www.kia.com/se/kopa/privatleasing/",
    note: "7 års garanti. Uppläggningsavgift 995 kr + admin 59 kr/mån.",
  },

  // ── 5 000–6 000 kr/mån ───────────────────────────────────────────────
  {
    id: "skoda-enyaq-85",
    brand: "Skoda",
    model: "Enyaq",
    trim: "85 Solid Edition",
    imageUrl: "/cars/skoda-enyaq.svg",
    monthlyPrice: 5195,
    downPayment: 10000,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 530,
    batteryKwh: 82,
    motorKw: 210,
    size: "suv",
    source: "Skoda Sverige",
    sourceUrl: "https://www.skoda.se/erbjudande/kampanj/erbjudande-enyaq-solid-edition",
    note: "10 000 kr första förhöjd avgift. Service ingår.",
  },
  {
    id: "polestar-2",
    brand: "Polestar",
    model: "2",
    trim: "Business Edition",
    imageUrl: "/cars/polestar-2.svg",
    monthlyPrice: 5495,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1500,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 540,
    batteryKwh: 79,
    motorKw: 220,
    size: "medium",
    source: "Polestar Sverige",
    sourceUrl: "https://www.polestar.com/se/offers/polestar-2-business-edition-private-lease/",
    note: "Pilot, Plus & Climate-paket ingår. Laddkabel ingår. Begränsat antal MY2026.",
  },
  {
    id: "hyundai-ioniq5",
    brand: "Hyundai",
    model: "IONIQ 5",
    trim: "RWD 84 kWh Essential",
    imageUrl: "/cars/hyundai-ioniq5.svg",
    monthlyPrice: 4995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 570,
    batteryKwh: 84,
    motorKw: 168,
    size: "suv",
    source: "Hyundai Sverige",
    sourceUrl: "https://www.hyundai.com/se/sv/kop/finans-forsakring/privatleasing.html",
    note: "Kampanjpris t.o.m. 31 mars 2026.",
  },
  {
    id: "skoda-enyaq-85-noinit",
    brand: "Skoda",
    model: "Enyaq",
    trim: "85 Solid Edition (utan insats)",
    imageUrl: "/cars/skoda-enyaq.svg",
    monthlyPrice: 5995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 530,
    batteryKwh: 82,
    motorKw: 210,
    size: "suv",
    source: "Skoda Sverige",
    sourceUrl: "https://privatleasing.skoda.se/valjmodell",
    note: "0 kr insats. Service ingår.",
  },

  // ── 6 000+ kr/mån ────────────────────────────────────────────────────
  {
    id: "vw-id4-gtx",
    brand: "Volkswagen",
    model: "ID.4",
    trim: "GTX 4MOTION",
    imageUrl: "/cars/volkswagen-id4.svg",
    monthlyPrice: 6855,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 510,
    batteryKwh: 82,
    motorKw: 220,
    size: "suv",
    source: "Volkswagen Sverige",
    sourceUrl: "https://www.volkswagen.se/sv/kop-en-vw/erbjudanden.html",
    note: "Fyrhjulsdrift.",
  },

  // ── Fiat ────────────────────────────────────────────────────────────
  {
    id: "fiat-600e",
    brand: "Fiat",
    model: "600",
    trim: "Electric",
    monthlyPrice: 2595,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 54,
    motorKw: 115,
    size: "compact",
    source: "Fiat Sverige",
    sourceUrl: "https://www.fiat.se/erbjudanden",
    note: "Kampanjpris. Servicepaket ingår.",
  },
  {
    id: "fiat-500e",
    brand: "Fiat",
    model: "500",
    trim: "Electric 42 kWh",
    monthlyPrice: 2795,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 310,
    batteryKwh: 42,
    motorKw: 87,
    size: "compact",
    source: "Fiat Sverige",
    sourceUrl: "https://www.fiat.se/aktuella-erbjudanden/erbjudande_500_electric",
    note: "Kampanjpris.",
  },

  // ── Citroën ─────────────────────────────────────────────────────────
  {
    id: "citroen-ec3-aircross",
    brand: "Citroën",
    model: "ë-C3 Aircross",
    trim: "Electric",
    monthlyPrice: 2799,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 300,
    batteryKwh: 45,
    motorKw: 83,
    size: "compact",
    source: "Citroën Sverige",
    sourceUrl: "https://www.citroen.se/kopa/privatleasing.html",
    note: "Service ingår via Ayvens.",
  },

  // ── BYD ─────────────────────────────────────────────────────────────
  {
    id: "byd-atto3",
    brand: "BYD",
    model: "Atto 3",
    trim: "Design",
    monthlyPrice: 3095,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 420,
    batteryKwh: 60.5,
    motorKw: 150,
    size: "compact",
    source: "Carplus",
    sourceUrl: "https://carplus.se/bilar/byd/",
    note: "Kampanjpris via Carplus. Uppläggningsavgift 995 kr.",
  },
  {
    id: "byd-seal-u",
    brand: "BYD",
    model: "Seal U",
    trim: "Design 87 kWh",
    monthlyPrice: 4995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 500,
    batteryKwh: 87,
    motorKw: 160,
    size: "suv",
    source: "BYD Sverige",
    sourceUrl: "https://bydauto.se/kopa/erbjudanden",
    note: "Uppläggningsavgift 995 kr + admin 60 kr/mån.",
  },

  // ── Opel ────────────────────────────────────────────────────────────
  {
    id: "opel-frontera-e",
    brand: "Opel",
    model: "Frontera",
    trim: "Electric",
    monthlyPrice: 3199,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 300,
    batteryKwh: 44,
    motorKw: 83,
    size: "compact",
    source: "Opel Sverige",
    sourceUrl: "https://www.opel.se/privatleasing.html",
    note: "Service och fabriksgaranti ingår via Ayvens.",
  },
  {
    id: "opel-mokka-e",
    brand: "Opel",
    model: "Mokka",
    trim: "Electric",
    monthlyPrice: 3999,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 54,
    motorKw: 115,
    size: "compact",
    source: "Opel Sverige",
    sourceUrl: "https://www.opel.se/privatleasing.html",
    note: "Service och fabriksgaranti ingår via Ayvens.",
  },

  // ── Renault ─────────────────────────────────────────────────────────
  {
    id: "renault-5",
    brand: "Renault",
    model: "5",
    trim: "E-Tech Electric",
    monthlyPrice: 3290,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 3000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 52,
    motorKw: 110,
    size: "compact",
    source: "Renault Sverige",
    sourceUrl: "https://www.renault.se/kopa/privatleasing",
    note: "3 000 mil/år ingår. Rörlig ränta (Stibor 90). Övermil 11 kr/mil. Kampanj t.o.m. 31 mars 2026.",
  },
  {
    id: "renault-megane",
    brand: "Renault",
    model: "Megane",
    trim: "E-Tech Electric EV60",
    monthlyPrice: 3990,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 3000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 450,
    batteryKwh: 60,
    motorKw: 160,
    size: "medium",
    source: "Renault Sverige",
    sourceUrl: "https://www.renault.se/kopa/privatleasing",
    note: "3 000 mil/år ingår. Rörlig ränta (Stibor 90). Övermil 11 kr/mil.",
  },
  {
    id: "renault-scenic",
    brand: "Renault",
    model: "Scenic",
    trim: "E-Tech Electric EV87",
    monthlyPrice: 3990,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 3000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 620,
    batteryKwh: 87,
    motorKw: 160,
    size: "suv",
    source: "Renault Sverige",
    sourceUrl: "https://www.renault.se/kopa/privatleasing",
    note: "3 000 mil/år ingår. Rörlig ränta (Stibor 90). Övermil 11 kr/mil.",
  },

  // ── MINI ────────────────────────────────────────────────────────────
  {
    id: "mini-cooper-se",
    brand: "MINI",
    model: "Cooper",
    trim: "SE Electric",
    monthlyPrice: 3395,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 54.2,
    motorKw: 160,
    size: "compact",
    source: "MINI Sverige",
    sourceUrl: "https://www.mini.se/sv_SE/hem/mini-finansiering/privatleasing.html",
    note: "Leveransavgift 9 000 kr ingår. Övermil 12,50 kr/mil. Admin 55 kr/mån.",
  },

  // ── Peugeot ─────────────────────────────────────────────────────────
  {
    id: "peugeot-e2008",
    brand: "Peugeot",
    model: "E-2008",
    trim: "GT",
    monthlyPrice: 3899,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 54,
    motorKw: 115,
    size: "compact",
    source: "Peugeot Sverige",
    sourceUrl: "https://www.peugeot.se/kop/finansiering/privatleasing.html",
    note: "Service ingår via Ayvens. Försäkring +395 kr/mån.",
  },
  {
    id: "ford-puma-gen-e",
    brand: "Ford",
    model: "Puma",
    trim: "Gen-E",
    monthlyPrice: 3995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 370,
    batteryKwh: 43,
    motorKw: 124,
    size: "compact",
    source: "Ford Sverige",
    sourceUrl: "https://ford.se/kopa/privatleasing/",
    note: "Service ingår via Arval.",
  },

  // ── Nissan ──────────────────────────────────────────────────────────
  {
    id: "nissan-leaf-52",
    brand: "Nissan",
    model: "Leaf",
    trim: "Engage 52 kWh",
    monthlyPrice: 4195,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 340,
    batteryKwh: 52,
    motorKw: 110,
    size: "compact",
    source: "Nissan Sverige",
    sourceUrl: "https://www.nissan.se/agande/agande-och-tjanster/nissan-finansiering/nissan-privatleasing.html",
    note: "Kampanjpris t.o.m. 31 mars 2026.",
  },
  {
    id: "nissan-leaf-75",
    brand: "Nissan",
    model: "Leaf",
    trim: "Engage 75 kWh Extended Range",
    monthlyPrice: 4595,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 460,
    batteryKwh: 75,
    motorKw: 160,
    size: "compact",
    source: "Nissan Sverige",
    sourceUrl: "https://www.nissan.se/agande/agande-och-tjanster/nissan-finansiering/nissan-privatleasing.html",
    note: "Kampanjpris t.o.m. 31 mars 2026.",
  },

  // ── Tesla ───────────────────────────────────────────────────────────
  {
    id: "tesla-model-y-rwd",
    brand: "Tesla",
    model: "Model Y",
    trim: "Standard RWD",
    monthlyPrice: 4995,
    downPayment: 2500,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 455,
    batteryKwh: 60,
    motorKw: 220,
    size: "suv",
    source: "Tesla Sverige",
    sourceUrl: "https://www.tesla.com/sv_se/modely/design",
    note: "2 500 kr insats. Övermil +256 kr/mån per 500 mil extra.",
  },
  {
    id: "peugeot-e3008",
    brand: "Peugeot",
    model: "E-3008",
    trim: "GT Standard Range",
    monthlyPrice: 4999,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 525,
    batteryKwh: 73,
    motorKw: 157,
    size: "suv",
    source: "Peugeot Sverige",
    sourceUrl: "https://www.peugeot.se/kop/finansiering/privatleasing.html",
    note: "Service ingår via Ayvens. Försäkring +395 kr/mån.",
  },
  {
    id: "ford-explorer-lr",
    brand: "Ford",
    model: "Explorer",
    trim: "Business Ed. Long Range RWD",
    monthlyPrice: 4995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 590,
    batteryKwh: 77,
    motorKw: 210,
    size: "suv",
    source: "Ford Sverige",
    sourceUrl: "https://ford.se/kopa/privatleasing/",
    note: "Service ingår via Arval.",
  },
  {
    id: "tesla-model-y-lr",
    brand: "Tesla",
    model: "Model Y",
    trim: "Long Range RWD",
    monthlyPrice: 5776,
    downPayment: 2500,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 600,
    batteryKwh: 79,
    motorKw: 220,
    size: "suv",
    source: "Tesla Sverige",
    sourceUrl: "https://www.tesla.com/sv_se/modely/design",
    note: "2 500 kr insats. Övermil +256 kr/mån per 500 mil extra.",
  },

  // ── Toyota ──────────────────────────────────────────────────────────
  {
    id: "toyota-bz4x",
    brand: "Toyota",
    model: "bZ4X",
    trim: "FWD",
    monthlyPrice: 5895,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 4500,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 490,
    batteryKwh: 71.4,
    motorKw: 150,
    size: "suv",
    source: "Toyota Sverige",
    sourceUrl: "https://www.toyota.se/bilar/kampanjer/privatleasing",
    note: "4 500 mil/år ingår. Övermil 12,50 kr/mil. Kampanj t.o.m. 31 mars 2026.",
  },

  // ── Nissan Ariya ────────────────────────────────────────────────────
  {
    id: "nissan-ariya-63",
    brand: "Nissan",
    model: "Ariya",
    trim: "Engage 63 kWh",
    monthlyPrice: 6095,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: true,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 63,
    motorKw: 160,
    size: "suv",
    source: "Nissan Sverige",
    sourceUrl: "https://www.nissan.se/fordon/fordon-utbud/ariya/kampanjer.html",
    note: "Vinterdäck ingår. Kampanjpris t.o.m. 31 mars 2026.",
  },

  // ── Audi ────────────────────────────────────────────────────────────
  {
    id: "audi-q4-etron",
    brand: "Audi",
    model: "Q4 e-tron",
    trim: "Proline",
    monthlyPrice: 6595,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 520,
    batteryKwh: 82,
    motorKw: 210,
    size: "suv",
    source: "Audi Sverige",
    sourceUrl: "https://privatleasing.audi.se/tillval/q4_e-tron_proline",
    note: "Serviceavtal ingår. Ränta 2,95 % för elbilar t.o.m. 31 maj 2026.",
  },
];
