/**
 * Faktiska privatleasing-erbjudanden för elbilar i Sverige.
 *
 * Uppdateras manuellt ungefär en gång per månad.
 * Källor: tillverkarnas officiella webbplatser och stora återförsäljare.
 *
 * Senast uppdaterad: 2026-03-17
 */

export interface LeasingOffer {
  id: string;
  brand: string;
  model: string;
  trim: string;
  imageUrl?: string;
  monthlyPrice: number;
  downPayment: number;
  contractMonths: number;
  annualMileage: number;
  serviceIncluded: boolean;
  winterTiresIncluded: boolean;
  insuranceIncluded: boolean;
  rangeKm: number;
  batteryKwh: number;
  motorKw: number;
  size: "compact" | "medium" | "suv" | "premium";
  source: string;
  sourceUrl: string;
  note?: string;
}

const MONTH_NAMES_SV = [
  "januari", "februari", "mars", "april", "maj", "juni",
  "juli", "augusti", "september", "oktober", "november", "december",
];

export function getLeasingPeriod(): string {
  return "mars 2026";  // uppdatera vid ny period
}

export const LEASING_SOURCE_NOTE =
  "Priserna är hämtade direkt från tillverkarnas och återförsäljarnas officiella webbplatser. Alla priser avser privatleasing exkl. eventuell uppläggningsavgift och administrationsavgift om inget annat anges. Erbjudanden kan ha ändrats sedan senaste uppdateringen (17 mars 2026).";

export const LEASING_OFFERS: LeasingOffer[] = [
  // ── Under 4 000 kr/mån ───────────────────────────────────────────────
  {
    id: "vw-id3-edition",
    brand: "Volkswagen",
    model: "ID.3",
    trim: "Pro Edition",
    imageUrl: "/cars/volkswagen-id3.svg",
    monthlyPrice: 3995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 430,
    batteryKwh: 58,
    motorKw: 150,
    size: "compact",
    source: "Volkswagen Sverige",
    sourceUrl: "https://www.volkswagen.se/sv/kop-en-vw/erbjudanden.html",
    note: "Även fr. 2 937 kr/mån med 35 000 kr insats. Service ingår.",
  },
  {
    id: "cupra-born",
    brand: "CUPRA",
    model: "Born",
    trim: "Edition 59 kWh",
    imageUrl: "/cars/cupra-born.svg",
    monthlyPrice: 4195,
    downPayment: 10000,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 424,
    batteryKwh: 59,
    motorKw: 150,
    size: "compact",
    source: "CUPRA Sverige",
    sourceUrl: "https://www.cupraofficial.se/kopa/erbjudande/born/privat/cupra-born",
    note: "10 000 kr första förhöjd avgift.",
  },

  // ── 4 000–5 000 kr/mån ───────────────────────────────────────────────
  {
    id: "volvo-ex30-plus",
    brand: "Volvo",
    model: "EX30",
    trim: "Plus",
    imageUrl: "/cars/volvo-ex30.svg",
    monthlyPrice: 3995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 344,
    batteryKwh: 51,
    motorKw: 200,
    size: "compact",
    source: "Volvo Cars Sverige",
    sourceUrl: "https://www.volvocars.com/se/l/erbjudanden/ex30/",
    note: "Care by Volvo privatleasing. Rörlig ränta (Stibor 90).",
  },
  {
    id: "volvo-ex30-plus-er",
    brand: "Volvo",
    model: "EX30",
    trim: "Plus Extended Range",
    imageUrl: "/cars/volvo-ex30.svg",
    monthlyPrice: 4495,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 476,
    batteryKwh: 69,
    motorKw: 200,
    size: "compact",
    source: "Volvo Cars Sverige",
    sourceUrl: "https://www.volvocars.com/se/l/erbjudanden/ex30/",
    note: "Care by Volvo privatleasing. Rörlig ränta (Stibor 90).",
  },
  {
    id: "mercedes-eqa-250",
    brand: "Mercedes-Benz",
    model: "EQA",
    trim: "250+ Special Edition",
    imageUrl: "/cars/mercedes-eqa.svg",
    monthlyPrice: 4195,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 490,
    batteryKwh: 70.5,
    motorKw: 140,
    size: "suv",
    source: "Mercedes-Benz Sverige",
    sourceUrl: "https://www.mercedes-benz.se/passengercars/finance/offers-private.html",
    note: "4 195 kr/mån mån 1–12, därefter 5 195 kr/mån. Beställ senast 31 mars 2026.",
  },
  {
    id: "mercedes-eqb-250",
    brand: "Mercedes-Benz",
    model: "EQB",
    trim: "250+ Special Edition",
    imageUrl: "/cars/mercedes-eqb.svg",
    monthlyPrice: 4695,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 465,
    batteryKwh: 70.5,
    motorKw: 140,
    size: "suv",
    source: "Mercedes-Benz Sverige",
    sourceUrl: "https://www.mercedes-benz.se/passengercars/finance/offers-private.html",
    note: "4 695 kr/mån mån 1–12, därefter 5 695 kr/mån. 7-sitsig. Beställ senast 31 mars 2026.",
  },
  {
    id: "kia-ev3-lr",
    brand: "Kia",
    model: "EV3",
    trim: "Long Range",
    imageUrl: "/cars/kia-ev3.svg",
    monthlyPrice: 4695,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 600,
    batteryKwh: 81.4,
    motorKw: 150,
    size: "compact",
    source: "Kia Sverige",
    sourceUrl: "https://www.kia.com/se/kopa/privatleasing/",
    note: "7 års garanti. Uppläggningsavgift 995 kr + admin 59 kr/mån.",
  },
  {
    id: "bmw-ix1",
    brand: "BMW",
    model: "iX1",
    trim: "eDrive20",
    imageUrl: "/cars/bmw-ix1.svg",
    monthlyPrice: 4795,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 440,
    batteryKwh: 64.7,
    motorKw: 150,
    size: "suv",
    source: "BMW Sverige",
    sourceUrl: "https://www.bmw.se/sv/bmw-financial-services-oversikt/erbjudanden/privaterbjudanden.html",
    note: "5-års servicepaket ingår. Vinterdäck +395 kr/mån. Övermil 12,50 kr/mil.",
  },
  {
    id: "kia-ev3-gt-line",
    brand: "Kia",
    model: "EV3",
    trim: "GT Line Long Range",
    imageUrl: "/cars/kia-ev3.svg",
    monthlyPrice: 5495,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 600,
    batteryKwh: 81.4,
    motorKw: 150,
    size: "compact",
    source: "Kia Sverige",
    sourceUrl: "https://www.kia.com/se/kopa/privatleasing/",
    note: "7 års garanti. Uppläggningsavgift 995 kr + admin 59 kr/mån.",
  },

  // ── 5 000–6 000 kr/mån ───────────────────────────────────────────────
  {
    id: "skoda-enyaq-85",
    brand: "Skoda",
    model: "Enyaq",
    trim: "85 Solid Edition",
    imageUrl: "/cars/skoda-enyaq.svg",
    monthlyPrice: 5195,
    downPayment: 10000,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 530,
    batteryKwh: 82,
    motorKw: 210,
    size: "suv",
    source: "Skoda Sverige",
    sourceUrl: "https://www.skoda.se/erbjudande/kampanj/erbjudande-enyaq-solid-edition",
    note: "10 000 kr första förhöjd avgift. Service ingår.",
  },
  {
    id: "polestar-2",
    brand: "Polestar",
    model: "2",
    trim: "Business Edition",
    imageUrl: "/cars/polestar-2.svg",
    monthlyPrice: 5495,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1500,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 540,
    batteryKwh: 79,
    motorKw: 220,
    size: "medium",
    source: "Polestar Sverige",
    sourceUrl: "https://www.polestar.com/se/offers/polestar-2-business-edition-private-lease/",
    note: "Pilot, Plus & Climate-paket ingår. Laddkabel ingår. Begränsat antal MY2026.",
  },
  {
    id: "hyundai-ioniq5",
    brand: "Hyundai",
    model: "IONIQ 5",
    trim: "RWD 84 kWh Essential",
    imageUrl: "/cars/hyundai-ioniq5.svg",
    monthlyPrice: 4995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 570,
    batteryKwh: 84,
    motorKw: 168,
    size: "suv",
    source: "Hyundai Sverige",
    sourceUrl: "https://www.hyundai.com/se/sv/kop/finans-forsakring/privatleasing.html",
    note: "Kampanjpris t.o.m. 31 mars 2026.",
  },
  {
    id: "skoda-enyaq-85-noinit",
    brand: "Skoda",
    model: "Enyaq",
    trim: "85 Solid Edition (utan insats)",
    imageUrl: "/cars/skoda-enyaq.svg",
    monthlyPrice: 5995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 530,
    batteryKwh: 82,
    motorKw: 210,
    size: "suv",
    source: "Skoda Sverige",
    sourceUrl: "https://privatleasing.skoda.se/valjmodell",
    note: "0 kr insats. Service ingår.",
  },

  // ── 6 000+ kr/mån ────────────────────────────────────────────────────
  {
    id: "vw-id4-gtx",
    brand: "Volkswagen",
    model: "ID.4",
    trim: "GTX 4MOTION",
    imageUrl: "/cars/volkswagen-id4.svg",
    monthlyPrice: 6855,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 510,
    batteryKwh: 82,
    motorKw: 220,
    size: "suv",
    source: "Volkswagen Sverige",
    sourceUrl: "https://www.volkswagen.se/sv/kop-en-vw/erbjudanden.html",
    note: "Fyrhjulsdrift.",
  },

  // ── Fiat ────────────────────────────────────────────────────────────
  {
    id: "fiat-600e",
    brand: "Fiat",
    model: "600",
    trim: "Electric",
    monthlyPrice: 2595,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 54,
    motorKw: 115,
    size: "compact",
    source: "Fiat Sverige",
    sourceUrl: "https://www.fiat.se/erbjudanden",
    note: "Kampanjpris. Servicepaket ingår.",
  },
  // ── Citroën ─────────────────────────────────────────────────────────
  {
    id: "citroen-ec3-aircross",
    brand: "Citroën",
    model: "ë-C3 Aircross",
    trim: "Electric",
    monthlyPrice: 2799,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 300,
    batteryKwh: 45,
    motorKw: 83,
    size: "compact",
    source: "Citroën Sverige",
    sourceUrl: "https://www.citroen.se/kopa/privatleasing.html",
    note: "Service ingår via Ayvens.",
  },

  // ── BYD ─────────────────────────────────────────────────────────────
  {
    id: "byd-atto3",
    brand: "BYD",
    model: "Atto 3",
    trim: "Design",
    monthlyPrice: 3095,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 420,
    batteryKwh: 60.5,
    motorKw: 150,
    size: "compact",
    source: "Carplus",
    sourceUrl: "https://carplus.se/bilar/byd/",
    note: "Kampanjpris via Carplus. Uppläggningsavgift 995 kr.",
  },
  {
    id: "byd-seal-u",
    brand: "BYD",
    model: "Seal U",
    trim: "Design 87 kWh",
    monthlyPrice: 4995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 500,
    batteryKwh: 87,
    motorKw: 160,
    size: "suv",
    source: "BYD Sverige",
    sourceUrl: "https://bydauto.se/kopa/erbjudanden",
    note: "Uppläggningsavgift 995 kr + admin 60 kr/mån.",
  },

  // ── Opel ────────────────────────────────────────────────────────────
  {
    id: "opel-frontera-e",
    brand: "Opel",
    model: "Frontera",
    trim: "Electric",
    monthlyPrice: 3199,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 300,
    batteryKwh: 44,
    motorKw: 83,
    size: "compact",
    source: "Opel Sverige",
    sourceUrl: "https://www.opel.se/privatleasing.html",
    note: "Service och fabriksgaranti ingår via Ayvens.",
  },
  {
    id: "opel-mokka-e",
    brand: "Opel",
    model: "Mokka",
    trim: "Electric",
    monthlyPrice: 3999,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 54,
    motorKw: 115,
    size: "compact",
    source: "Opel Sverige",
    sourceUrl: "https://www.opel.se/privatleasing.html",
    note: "Service och fabriksgaranti ingår via Ayvens.",
  },

  // ── Renault ─────────────────────────────────────────────────────────
  {
    id: "renault-5",
    brand: "Renault",
    model: "5",
    trim: "E-Tech Electric",
    monthlyPrice: 3290,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 3000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 52,
    motorKw: 110,
    size: "compact",
    source: "Renault Sverige",
    sourceUrl: "https://www.renault.se/kopa/privatleasing",
    note: "3 000 mil/år ingår. Rörlig ränta (Stibor 90). Övermil 11 kr/mil. Kampanj t.o.m. 31 mars 2026.",
  },
  {
    id: "renault-megane",
    brand: "Renault",
    model: "Megane",
    trim: "E-Tech Electric EV60",
    monthlyPrice: 3990,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 3000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 450,
    batteryKwh: 60,
    motorKw: 160,
    size: "medium",
    source: "Renault Sverige",
    sourceUrl: "https://www.renault.se/kopa/privatleasing",
    note: "3 000 mil/år ingår. Rörlig ränta (Stibor 90). Övermil 11 kr/mil.",
  },
  {
    id: "renault-scenic",
    brand: "Renault",
    model: "Scenic",
    trim: "E-Tech Electric EV87",
    monthlyPrice: 3990,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 3000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 620,
    batteryKwh: 87,
    motorKw: 160,
    size: "suv",
    source: "Renault Sverige",
    sourceUrl: "https://www.renault.se/kopa/privatleasing",
    note: "3 000 mil/år ingår. Rörlig ränta (Stibor 90). Övermil 11 kr/mil.",
  },

  // ── MINI ────────────────────────────────────────────────────────────
  {
    id: "mini-cooper-se",
    brand: "MINI",
    model: "Cooper",
    trim: "SE Electric",
    monthlyPrice: 3395,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 54.2,
    motorKw: 160,
    size: "compact",
    source: "MINI Sverige",
    sourceUrl: "https://www.mini.se/sv_SE/hem/mini-finansiering/privatleasing.html",
    note: "Leveransavgift 9 000 kr ingår. Övermil 12,50 kr/mil. Admin 55 kr/mån.",
  },

  // ── Peugeot ─────────────────────────────────────────────────────────
  {
    id: "peugeot-e2008",
    brand: "Peugeot",
    model: "E-2008",
    trim: "GT",
    monthlyPrice: 3899,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 54,
    motorKw: 115,
    size: "compact",
    source: "Peugeot Sverige",
    sourceUrl: "https://www.peugeot.se/kop/finansiering/privatleasing.html",
    note: "Service ingår via Ayvens. Försäkring +395 kr/mån.",
  },
  {
    id: "ford-puma-gen-e",
    brand: "Ford",
    model: "Puma",
    trim: "Gen-E",
    monthlyPrice: 3995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 370,
    batteryKwh: 43,
    motorKw: 124,
    size: "compact",
    source: "Ford Sverige",
    sourceUrl: "https://ford.se/kopa/privatleasing/",
    note: "Service ingår via Arval.",
  },

  // ── Nissan ──────────────────────────────────────────────────────────
  {
    id: "nissan-leaf-52",
    brand: "Nissan",
    model: "Leaf",
    trim: "Engage 52 kWh",
    monthlyPrice: 4195,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 340,
    batteryKwh: 52,
    motorKw: 110,
    size: "compact",
    source: "Nissan Sverige",
    sourceUrl: "https://www.nissan.se/agande/agande-och-tjanster/nissan-finansiering/nissan-privatleasing.html",
    note: "Kampanjpris t.o.m. 31 mars 2026.",
  },
  {
    id: "nissan-leaf-75",
    brand: "Nissan",
    model: "Leaf",
    trim: "Engage 75 kWh Extended Range",
    monthlyPrice: 4595,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 460,
    batteryKwh: 75,
    motorKw: 160,
    size: "compact",
    source: "Nissan Sverige",
    sourceUrl: "https://www.nissan.se/agande/agande-och-tjanster/nissan-finansiering/nissan-privatleasing.html",
    note: "Kampanjpris t.o.m. 31 mars 2026.",
  },

  // ── Tesla ───────────────────────────────────────────────────────────
  {
    id: "tesla-model-y-rwd",
    brand: "Tesla",
    model: "Model Y",
    trim: "Standard RWD",
    monthlyPrice: 4995,
    downPayment: 2500,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 455,
    batteryKwh: 60,
    motorKw: 220,
    size: "suv",
    source: "Tesla Sverige",
    sourceUrl: "https://www.tesla.com/sv_se/modely/design",
    note: "2 500 kr insats. Övermil +256 kr/mån per 500 mil extra.",
  },
  {
    id: "peugeot-e3008",
    brand: "Peugeot",
    model: "E-3008",
    trim: "GT Standard Range",
    monthlyPrice: 4999,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 525,
    batteryKwh: 73,
    motorKw: 157,
    size: "suv",
    source: "Peugeot Sverige",
    sourceUrl: "https://www.peugeot.se/kop/finansiering/privatleasing.html",
    note: "Service ingår via Ayvens. Försäkring +395 kr/mån.",
  },
  {
    id: "ford-explorer-lr",
    brand: "Ford",
    model: "Explorer",
    trim: "Business Ed. Long Range RWD",
    monthlyPrice: 4995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 590,
    batteryKwh: 77,
    motorKw: 210,
    size: "suv",
    source: "Ford Sverige",
    sourceUrl: "https://ford.se/kopa/privatleasing/",
    note: "Service ingår via Arval.",
  },
  {
    id: "tesla-model-y-lr",
    brand: "Tesla",
    model: "Model Y",
    trim: "Long Range RWD",
    monthlyPrice: 5776,
    downPayment: 2500,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 600,
    batteryKwh: 79,
    motorKw: 220,
    size: "suv",
    source: "Tesla Sverige",
    sourceUrl: "https://www.tesla.com/sv_se/modely/design",
    note: "2 500 kr insats. Övermil +256 kr/mån per 500 mil extra.",
  },

  // ── Toyota ──────────────────────────────────────────────────────────
  {
    id: "toyota-bz4x",
    brand: "Toyota",
    model: "bZ4X",
    trim: "FWD",
    monthlyPrice: 5895,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 4500,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 490,
    batteryKwh: 71.4,
    motorKw: 150,
    size: "suv",
    source: "Toyota Sverige",
    sourceUrl: "https://www.toyota.se/bilar/kampanjer/privatleasing",
    note: "4 500 mil/år ingår. Övermil 12,50 kr/mil. Kampanj t.o.m. 31 mars 2026.",
  },

  // ── Nissan Ariya ────────────────────────────────────────────────────
  {
    id: "nissan-ariya-63",
    brand: "Nissan",
    model: "Ariya",
    trim: "Engage 63 kWh",
    monthlyPrice: 6095,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: true,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 63,
    motorKw: 160,
    size: "suv",
    source: "Nissan Sverige",
    sourceUrl: "https://www.nissan.se/fordon/fordon-utbud/ariya/kampanjer.html",
    note: "Vinterdäck ingår. Kampanjpris t.o.m. 31 mars 2026.",
  },

  // ── Audi ────────────────────────────────────────────────────────────
  {
    id: "audi-q4-etron",
    brand: "Audi",
    model: "Q4 e-tron",
    trim: "Proline",
    monthlyPrice: 6595,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 520,
    batteryKwh: 82,
    motorKw: 210,
    size: "suv",
    source: "Audi Sverige",
    sourceUrl: "https://privatleasing.audi.se/tillval/q4_e-tron_proline",
    note: "Serviceavtal ingår. Ränta 2,95 % för elbilar t.o.m. 31 maj 2026.",
  },
  {
    id: "audi-q4-sportback",
    brand: "Audi",
    model: "Q4 Sportback e-tron",
    trim: "Proline",
    monthlyPrice: 6995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 520,
    batteryKwh: 82,
    motorKw: 210,
    size: "suv",
    source: "Audi Sverige",
    sourceUrl: "https://privatleasing.audi.se/tillval/q4_sportback_e-tron_proline",
    note: "Sportback-variant. Serviceavtal ingår. Ränta 2,95 % t.o.m. 31 maj 2026.",
  },
  {
    id: "audi-a6-sportback-etron",
    brand: "Audi",
    model: "A6 Sportback e-tron",
    trim: "Performance",
    monthlyPrice: 8995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 720,
    batteryKwh: 100,
    motorKw: 270,
    size: "premium",
    source: "Audi Sverige",
    sourceUrl: "https://privatleasing.audi.se/",
    note: "Serviceavtal ingår. Ränta 2,95 % t.o.m. 31 maj 2026.",
  },
  {
    id: "audi-a6-avant-etron",
    brand: "Audi",
    model: "A6 Avant e-tron",
    trim: "Performance",
    monthlyPrice: 9095,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 700,
    batteryKwh: 100,
    motorKw: 270,
    size: "premium",
    source: "Audi Sverige",
    sourceUrl: "https://privatleasing.audi.se/",
    note: "Kombiversion. Serviceavtal ingår. Ränta 2,95 % t.o.m. 31 maj 2026.",
  },

  // ── MG ──────────────────────────────────────────────────────────────
  {
    id: "mg-zs-ev",
    brand: "MG",
    model: "ZS EV",
    trim: "Comfort",
    monthlyPrice: 2695,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 320,
    batteryKwh: 51,
    motorKw: 130,
    size: "compact",
    source: "MG Motor Sverige",
    sourceUrl: "https://mgmotor.se/privatleasing",
    note: "7 års garanti. Service ingår.",
  },
  {
    id: "mg-mg5",
    brand: "MG",
    model: "MG5",
    trim: "Electric Comfort",
    monthlyPrice: 2995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 400,
    batteryKwh: 61,
    motorKw: 130,
    size: "medium",
    source: "MG Motor Sverige",
    sourceUrl: "https://mgmotor.se/privatleasing",
    note: "Kombi. 7 års garanti. Service ingår.",
  },
  {
    id: "mg-mg4-standard",
    brand: "MG",
    model: "MG4",
    trim: "Standard Range",
    monthlyPrice: 3295,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 350,
    batteryKwh: 51,
    motorKw: 125,
    size: "compact",
    source: "MG Motor Sverige",
    sourceUrl: "https://mgmotor.se/privatleasing",
    note: "7 års garanti. Service ingår.",
  },
  {
    id: "mg-mg4-luxury",
    brand: "MG",
    model: "MG4",
    trim: "Luxury Extended Range",
    monthlyPrice: 3895,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 450,
    batteryKwh: 64,
    motorKw: 150,
    size: "compact",
    source: "MG Motor Sverige",
    sourceUrl: "https://mgmotor.se/privatleasing",
    note: "7 års garanti. Service ingår.",
  },
  {
    id: "mg-mg4-xpower",
    brand: "MG",
    model: "MG4",
    trim: "XPower AWD",
    monthlyPrice: 3995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 385,
    batteryKwh: 64,
    motorKw: 320,
    size: "compact",
    source: "MG Motor Sverige",
    sourceUrl: "https://mgmotor.se/privatleasing",
    note: "Fyrhjulsdrift. 435 hk. 7 års garanti. Service ingår.",
  },

  // ── Smart ─────────────────────────────────────────────────────────
  {
    id: "smart-1-pro",
    brand: "Smart",
    model: "#1",
    trim: "Pro",
    monthlyPrice: 4295,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: true,
    rangeKm: 310,
    batteryKwh: 49,
    motorKw: 200,
    size: "compact",
    source: "Smart Sverige",
    sourceUrl: "https://se.smart.com/sv/financing-and-leasing/private-leasing/",
    note: "Service och försäkring ingår via NF Fleet. 49 kWh LFP-batteri.",
  },
  {
    id: "smart-1-proplus",
    brand: "Smart",
    model: "#1",
    trim: "Pro+",
    monthlyPrice: 4995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: true,
    rangeKm: 420,
    batteryKwh: 66,
    motorKw: 200,
    size: "compact",
    source: "Smart Sverige",
    sourceUrl: "https://se.smart.com/sv/financing-and-leasing/private-leasing/",
    note: "Service och försäkring ingår via NF Fleet. 66 kWh NMC-batteri.",
  },
  {
    id: "smart-3-proplus",
    brand: "Smart",
    model: "#3",
    trim: "Pro+",
    monthlyPrice: 5795,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: true,
    rangeKm: 435,
    batteryKwh: 66,
    motorKw: 200,
    size: "suv",
    source: "Smart Sverige",
    sourceUrl: "https://se.smart.com/sv/financing-and-leasing/private-leasing/",
    note: "Fastback SUV. Service och försäkring ingår via NF Fleet.",
  },

  // ── Xpeng ─────────────────────────────────────────────────────────
  {
    id: "xpeng-g6-sr",
    brand: "Xpeng",
    model: "G6",
    trim: "Standard Range RWD",
    monthlyPrice: 5995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: true,
    rangeKm: 435,
    batteryKwh: 68.5,
    motorKw: 190,
    size: "suv",
    source: "Xpeng Sverige",
    sourceUrl: "https://event.xpeng.com/se/s085ny.html",
    note: "Service, försäkring och garanterat restvärde ingår via NF Fleet. Kampanj t.o.m. 31 mars 2026.",
  },
  {
    id: "xpeng-g6-lr",
    brand: "Xpeng",
    model: "G6",
    trim: "Long Range RWD",
    monthlyPrice: 6295,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: true,
    rangeKm: 535,
    batteryKwh: 80.8,
    motorKw: 210,
    size: "suv",
    source: "Xpeng Sverige",
    sourceUrl: "https://event.xpeng.com/se/s085ny.html",
    note: "Service, försäkring och garanterat restvärde ingår via NF Fleet.",
  },

  // ── Volvo (ytterligare) ───────────────────────────────────────────
  {
    id: "volvo-ex40-plus",
    brand: "Volvo",
    model: "EX40",
    trim: "Plus Single Motor",
    monthlyPrice: 4195,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 460,
    batteryKwh: 69,
    motorKw: 175,
    size: "suv",
    source: "Volvo Cars Sverige",
    sourceUrl: "https://www.volvocars.com/se/l/erbjudanden/ex40/",
    note: "Care by Volvo privatleasing. Rörlig ränta (Stibor 90).",
  },
  {
    id: "volvo-ex60-plus",
    brand: "Volvo",
    model: "EX60",
    trim: "Plus Single Motor",
    monthlyPrice: 8995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 600,
    batteryKwh: 101,
    motorKw: 205,
    size: "premium",
    source: "Volvo Cars Sverige",
    sourceUrl: "https://www.volvocars.com/se/l/erbjudanden/ex60/",
    note: "Care by Volvo privatleasing. Rörlig ränta (Stibor 90). Ny modell 2026.",
  },

  // ── BMW (ytterligare) ─────────────────────────────────────────────
  {
    id: "bmw-ix3-neue-klasse",
    brand: "BMW",
    model: "iX3",
    trim: "50 xDrive Active Edition",
    monthlyPrice: 4795,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 678,
    batteryKwh: 109,
    motorKw: 345,
    size: "suv",
    source: "BMW Sverige",
    sourceUrl: "https://www.bmw.se/sv/bmw-financial-services-oversikt/erbjudanden/privaterbjudanden.html",
    note: "Neue Klasse-plattform. Laddning upp till 400 kW. 5-års servicepaket ingår. Övermil 12,50 kr/mil. Erbjudande t.o.m. 30 juni 2026.",
  },

  // ── Hyundai (ytterligare) ─────────────────────────────────────────
  {
    id: "hyundai-ioniq6",
    brand: "Hyundai",
    model: "IONIQ 6",
    trim: "RWD 84 kWh",
    monthlyPrice: 4995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: false,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 614,
    batteryKwh: 84,
    motorKw: 168,
    size: "medium",
    source: "Hyundai Sverige",
    sourceUrl: "https://www.hyundai.com/se/sv/kop/finans-forsakring/privatleasing/ioniq-6-privatleasing.html",
    note: "Aerodynamisk sedan. 800V-arkitektur – snabbladdning 18 min (10→80 %). 5 års garanti. Service ingår ej.",
  },
  {
    id: "hyundai-kona-electric",
    brand: "Hyundai",
    model: "Kona Electric",
    trim: "65 kWh",
    monthlyPrice: 4995,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: false,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 512,
    batteryKwh: 65.4,
    motorKw: 150,
    size: "compact",
    source: "Hyundai Sverige",
    sourceUrl: "https://www.hyundai.com/se/sv/kop/finans-forsakring/privatleasing.html",
    note: "Kompakt elbils-SUV. 5 års garanti. Service ingår ej.",
  },

  // ── Tesla (ytterligare) ───────────────────────────────────────────
  {
    id: "tesla-model-3-highland",
    brand: "Tesla",
    model: "Model 3",
    trim: "Highland RWD",
    monthlyPrice: 6690,
    downPayment: 2500,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 513,
    batteryKwh: 60,
    motorKw: 208,
    size: "medium",
    source: "Tesla Sverige",
    sourceUrl: "https://www.tesla.com/sv_se/model3/design",
    note: "2 500 kr insats. Highland-facelift.",
  },

  // ── Jeep ──────────────────────────────────────────────────────────
  {
    id: "jeep-avenger-electric",
    brand: "Jeep",
    model: "Avenger",
    trim: "Electric Longitude",
    monthlyPrice: 6495,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: true,
    rangeKm: 400,
    batteryKwh: 54,
    motorKw: 115,
    size: "compact",
    source: "Carplus",
    sourceUrl: "https://carplus.se/bilar/jeep/jeep-avenger-electric-longitude-2025/",
    note: "Försäkring, service, vägassistans och betalningsskydd ingår via Carplus.",
  },

  // ── Lexus ─────────────────────────────────────────────────────────
  {
    id: "lexus-rz-450e",
    brand: "Lexus",
    model: "RZ",
    trim: "450e AWD",
    monthlyPrice: 6475,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1500,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 395,
    batteryKwh: 71.4,
    motorKw: 230,
    size: "suv",
    source: "Lexus Sverige",
    sourceUrl: "https://www.lexus.se/privatleasing",
    note: "Fyrhjulsdrift. 1 500 mil/år. Service ingår.",
  },

  // ── Alfa Romeo ────────────────────────────────────────────────────
  {
    id: "alfa-romeo-junior-veloce",
    brand: "Alfa Romeo",
    model: "Junior",
    trim: "Elettrica Veloce",
    monthlyPrice: 3495,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 322,
    batteryKwh: 54,
    motorKw: 207,
    size: "compact",
    source: "Alfa Romeo Sverige",
    sourceUrl: "https://www.alfaromeo.se/erbjudanden",
    note: "Kampanjpris. 280 hk, sportchassi, Brembo-bromsar. Uppläggningsavgift 995 kr + admin 59 kr/mån.",
  },

  // ── Porsche ───────────────────────────────────────────────────────
  {
    id: "porsche-macan-4-electric",
    brand: "Porsche",
    model: "Macan 4",
    trim: "Electric",
    monthlyPrice: 8800,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1500,
    serviceIncluded: false,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 613,
    batteryKwh: 100,
    motorKw: 300,
    size: "premium",
    source: "Alleasing / Porsche Center",
    sourceUrl: "https://www.alleasing.se/porsche/macan",
    note: "800V-arkitektur. Snabbladdning 10→80 % på 21 min. Service ingår ej.",
  },
  {
    id: "porsche-taycan",
    brand: "Porsche",
    model: "Taycan",
    trim: "RWD Performance Battery Plus",
    monthlyPrice: 13999,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1500,
    serviceIncluded: false,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 484,
    batteryKwh: 93,
    motorKw: 280,
    size: "premium",
    source: "Porsche Center",
    sourceUrl: "https://dealer.porsche.com/se/linkoping/sv-SE/Privatleasing/Porsche-Taycan",
    note: "800V-arkitektur. Bakhjulsdrift. Service ingår ej.",
  },

  // ── Honda ─────────────────────────────────────────────────────────
  {
    id: "honda-eny1",
    brand: "Honda",
    model: "e:Ny1",
    trim: "Advance",
    monthlyPrice: 8230,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1500,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 412,
    batteryKwh: 68.8,
    motorKw: 150,
    size: "compact",
    source: "Honda Sverige",
    sourceUrl: "https://www.honda.se/erbjudanden",
    note: "Service ingår. 1 500 mil/år.",
  },

  // ── Kia (ytterligare) ──────────────────────────────────────────────
  {
    id: "kia-ev6-lr",
    brand: "Kia",
    model: "EV6",
    trim: "Long Range RWD",
    monthlyPrice: 4695,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1500,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 582,
    batteryKwh: 84,
    motorKw: 168,
    size: "medium",
    source: "Kia Sverige",
    sourceUrl: "https://www.kia.com/se/kopa/privatleasing/",
    note: "7 års garanti. 800V-laddning. 1 500 mil/år. Uppläggningsavgift 995 kr + admin 59 kr/mån.",
  },

  // ── Audi (ytterligare) ────────────────────────────────────────────
  {
    id: "audi-q6-etron",
    brand: "Audi",
    model: "Q6 e-tron",
    trim: "quattro Proline",
    monthlyPrice: 8495,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1000,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 625,
    batteryKwh: 100,
    motorKw: 285,
    size: "premium",
    source: "Audi Sverige",
    sourceUrl: "https://www.audi.se/sv/models/q6-e-tron/q6-e-tron/finansiering/",
    note: "800V-teknik, laddning upp till 270 kW. Kampanjränta 2,95 % t.o.m. 31 maj 2026.",
  },

  // ── Subaru ────────────────────────────────────────────────────────
  {
    id: "subaru-solterra",
    brand: "Subaru",
    model: "Solterra",
    trim: "AWD",
    monthlyPrice: 7127,
    downPayment: 0,
    contractMonths: 36,
    annualMileage: 1500,
    serviceIncluded: true,
    winterTiresIncluded: false,
    insuranceIncluded: false,
    rangeKm: 465,
    batteryKwh: 71.4,
    motorKw: 160,
    size: "suv",
    source: "Subaru Sverige",
    sourceUrl: "https://www.subaru.se/privatleasing",
    note: "Symmetrisk fyrhjulsdrift. 1 500 mil/år. Service ingår.",
  },
];
